package main

import (
	"go/ast"
	"go/parser"
	"go/token"
	"strconv"
	"strings"
	"testing"
)

const clientsetSource = `// Code generated by client-gen. DO NOT EDIT.

package kubernetes

import (
	fmt "fmt"
	http "net/http"

	discovery "k8s.io/client-go/discovery"
	appsv1 "k8s.io/client-go/kubernetes/typed/apps/v1"
	appsv1beta1 "k8s.io/client-go/kubernetes/typed/apps/v1beta1"
	corev1 "k8s.io/client-go/kubernetes/typed/core/v1"
	rest "k8s.io/client-go/rest"
	flowcontrol "k8s.io/client-go/util/flowcontrol"
)

type Interface interface {
	Discovery() discovery.DiscoveryInterface
	// AppsV1 doc
	AppsV1() appsv1.AppsV1Interface
	AppsV1beta1() appsv1beta1.AppsV1beta1Interface
	CoreV1() corev1.CoreV1Interface
}

type Clientset struct {
	*discovery.DiscoveryClient
	appsV1      *appsv1.AppsV1Client
	appsV1beta1 *appsv1beta1.AppsV1beta1Client
	coreV1      *corev1.CoreV1Client
}

// AppsV1 doc
func (c *Clientset) AppsV1() appsv1.AppsV1Interface {
	return c.appsV1
}

// AppsV1beta1 doc
func (c *Clientset) AppsV1beta1() appsv1beta1.AppsV1beta1Interface {
	return c.appsV1beta1
}

func (c *Clientset) CoreV1() corev1.CoreV1Interface {
	return c.coreV1
}

func (c *Clientset) Discovery() discovery.DiscoveryInterface {
	return c.DiscoveryClient
}

func NewForConfigAndClient(c *rest.Config, httpClient *http.Client) (*Clientset, error) {
	configShallowCopy := *c
	if configShallowCopy.RateLimiter == nil {
		configShallowCopy.RateLimiter = flowcontrol.NewTokenBucketRateLimiter(1, 1)
	}
	var cs Clientset
	var err error
	cs.appsV1, err = appsv1.NewForConfigAndClient(&configShallowCopy, httpClient)
	if err != nil {
		return nil, err
	}
	cs.appsV1beta1, err = appsv1beta1.NewForConfigAndClient(&configShallowCopy, httpClient)
	if err != nil {
		return nil, err
	}
	cs.coreV1, err = corev1.NewForConfigAndClient(&configShallowCopy, httpClient)
	if err != nil {
		return nil, fmt.Errorf("core: %w", err)
	}
	cs.DiscoveryClient, err = discovery.NewDiscoveryClientForConfigAndClient(&configShallowCopy, httpClient)
	if err != nil {
		return nil, err
	}
	return &cs, nil
}

func New(c rest.Interface) *Clientset {
	var cs Clientset
	cs.appsV1 = appsv1.New(c)
	cs.appsV1beta1 = appsv1beta1.New(c)
	cs.coreV1 = corev1.New(c)
	cs.DiscoveryClient = discovery.NewDiscoveryClient(c)
	return &cs
}
`

func parseOutput(t *testing.T, src []byte) *ast.File {
	t.Helper()
	f, err := parser.ParseFile(token.NewFileSet(), "out.go", src, parser.ParseComments)
	if err != nil {
		t.Fatalf("output does not parse: %v\n%s", err, src)
	}
	return f
}

func assignedClients(t *testing.T, f *ast.File, fn string) []string {
	t.Helper()
	var out []string
	for _, decl := range f.Decls {
		d, ok := decl.(*ast.FuncDecl)
		if !ok || d.Recv != nil || d.Name.Name != fn {
			continue
		}
		for _, stmt := range d.Body.List {
			assign, ok := stmt.(*ast.AssignStmt)
			if !ok {
				continue
			}
			if sel, ok := assign.Lhs[0].(*ast.SelectorExpr); ok && sel.Sel.Name != "DiscoveryClient" {
				out = append(out, sel.Sel.Name)
			}
		}
	}
	return out
}

func unusedImports(f *ast.File) []string {
	used := map[string]bool{}
	ast.Inspect(f, func(n ast.Node) bool {
		if sel, ok := n.(*ast.SelectorExpr); ok {
			if id, ok := sel.X.(*ast.Ident); ok {
				used[id.Name] = true
			}
		}
		return true
	})
	var unused []string
	for _, imp := range f.Imports {
		path, _ := strconv.Unquote(imp.Path.Value)
		name := path[strings.LastIndex(path, "/")+1:]
		if imp.Name != nil {
			name = imp.Name.Name
		}
		if !used[name] {
			unused = append(unused, path)
		}
	}
	return unused
}

func TestLeanClientsetKeepsExactlyTheListedGroupVersions(t *testing.T) {
	out, err := leanClientset([]byte(clientsetSource), []groupVersion{{"apps", "v1"}, {"core", "v1"}})
	if err != nil {
		t.Fatal(err)
	}
	f := parseOutput(t, out)
	want := "appsV1,coreV1"
	for _, fn := range []string{"NewForConfigAndClient", "New"} {
		if got := strings.Join(assignedClients(t, f, fn), ","); got != want {
			t.Errorf("%s initialises %q, want %q", fn, got, want)
		}
	}
	text := string(out)
	for _, gone := range []string{"appsv1beta1", "AppsV1beta1", "appsV1beta1"} {
		if strings.Contains(text, gone) {
			t.Errorf("output still mentions %s:\n%s", gone, text)
		}
	}
	if !strings.HasPrefix(text, "//go:build js\n") {
		t.Errorf("output lacks the js build constraint:\n%s", text)
	}
	if !strings.Contains(text, "AppsV1 doc") {
		t.Errorf("doc comment of a kept method was dropped")
	}
	if strings.Contains(text, "AppsV1beta1 doc") {
		t.Errorf("doc comment of a removed method was kept")
	}
}

func TestLeanClientsetLeavesNoUnusedImport(t *testing.T) {
	out, err := leanClientset([]byte(clientsetSource), []groupVersion{{"core", "v1"}})
	if err != nil {
		t.Fatal(err)
	}
	if unused := unusedImports(parseOutput(t, out)); len(unused) != 0 {
		t.Errorf("unused imports left: %v", unused)
	}
}

func TestLeanClientsetNamesMissingGroupVersion(t *testing.T) {
	_, err := leanClientset([]byte(clientsetSource), []groupVersion{{"apps", "v1"}, {"rbac", "v1"}})
	if err == nil || !strings.Contains(err.Error(), "rbac/v1") {
		t.Fatalf("want an error naming rbac/v1, got %v", err)
	}
}

func TestLeanClientsetNamesMissingConstructor(t *testing.T) {
	src := strings.Replace(clientsetSource, "func New(", "func Renamed(", 1)
	_, err := leanClientset([]byte(src), []groupVersion{{"apps", "v1"}})
	if err == nil || !strings.Contains(err.Error(), "New") {
		t.Fatalf("want an error naming New, got %v", err)
	}
}

func TestLeanClientsetNamesGroupVersionMissingFromAConstructor(t *testing.T) {
	src := strings.Replace(clientsetSource, "\tcs.coreV1 = corev1.New(c)\n", "", 1)
	_, err := leanClientset([]byte(src), []groupVersion{{"core", "v1"}})
	if err == nil || !strings.Contains(err.Error(), "core/v1") || !strings.Contains(err.Error(), "New") {
		t.Fatalf("want an error naming core/v1 and New, got %v", err)
	}
}

func TestLeanClientsetFailsWhenDroppedAssignmentFollowedByNonStandardGuard(t *testing.T) {
	_, err := leanClientset([]byte(clientsetSource), []groupVersion{{"apps", "v1"}})
	if err == nil {
		t.Fatal("expected error when dropped assignment is followed by non-standard guard")
	}
	if !strings.Contains(err.Error(), "NewForConfigAndClient") {
		t.Errorf("error %q should name constructor NewForConfigAndClient", err)
	}
	if !strings.Contains(err.Error(), "core/v1") {
		t.Errorf("error %q should name group-version core/v1", err)
	}
}

func TestPruneImportsDropsImportWhenLocalVariableSharesPackageName(t *testing.T) {
	src := `package kubernetes

import (
	discovery "k8s.io/client-go/discovery"
	appsv1 "k8s.io/client-go/kubernetes/typed/apps/v1"
	rest "k8s.io/client-go/rest"
	flowcontrol "k8s.io/client-go/util/flowcontrol"
)

type Interface interface {
	Discovery() discovery.DiscoveryInterface
	AppsV1() appsv1.AppsV1Interface
}

type Clientset struct {
	*discovery.DiscoveryClient
	appsV1 *appsv1.AppsV1Client
}

func (c *Clientset) AppsV1() appsv1.AppsV1Interface { return c.appsV1 }
func (c *Clientset) Discovery() discovery.DiscoveryInterface { return c.DiscoveryClient }

func NewForConfigAndClient(c *rest.Config) (*Clientset, error) {
	var cs Clientset
	var err error
	cs.appsV1, err = appsv1.NewForConfigAndClient(c, nil)
	if err != nil {
		return nil, err
	}
	cs.DiscoveryClient, err = discovery.NewDiscoveryClientForConfigAndClient(c, nil)
	if err != nil {
		return nil, err
	}
	type local struct{ RateLimiter int }
	flowcontrol := local{}
	_ = flowcontrol.RateLimiter
	return &cs, nil
}

func New(c rest.Interface) *Clientset {
	var cs Clientset
	cs.appsV1 = appsv1.New(c)
	cs.DiscoveryClient = discovery.NewDiscoveryClient(c)
	return &cs
}
`
	out, err := leanClientset([]byte(src), []groupVersion{{"apps", "v1"}})
	if err != nil {
		t.Fatal(err)
	}
	text := string(out)
	if strings.Contains(text, "k8s.io/client-go/util/flowcontrol") {
		t.Errorf("flowcontrol import should be pruned even though a local variable shares its name:\n%s", text)
	}
}

func TestLeanInformerFactoryFailsWhenStubImportAliasDiffers(t *testing.T) {
	src := strings.Replace(factorySource, `cache "k8s.io/client-go/tools/cache"`, `mycache "k8s.io/client-go/tools/cache"`, 1)
	_, err := leanInformerFactory([]byte(src), []string{"apps"})
	if err == nil {
		t.Fatal("expected error when stub import alias differs from existing import alias")
	}
	for _, want := range []string{"k8s.io/client-go/tools/cache", "mycache", "cache"} {
		if !strings.Contains(err.Error(), want) {
			t.Errorf("error %q should contain %q", err, want)
		}
	}
}

const factorySource = `package informers

import (
	cache "k8s.io/client-go/tools/cache"
	apps "k8s.io/client-go/informers/apps"
	core "k8s.io/client-go/informers/core"
	internalinterfaces "k8s.io/client-go/informers/internalinterfaces"
)

type sharedInformerFactory struct{}

type SharedInformerFactory interface {
	internalinterfaces.SharedInformerFactory
	InformerFor() cache.SharedIndexInformer
	Apps() apps.Interface
	Core() core.Interface
}

func (f *sharedInformerFactory) Apps() apps.Interface {
	return apps.New(f)
}

func (f *sharedInformerFactory) Core() core.Interface {
	return core.New(f)
}
`

func TestLeanInformerFactoryKeepsListedGroups(t *testing.T) {
	out, err := leanInformerFactory([]byte(factorySource), []string{"apps"})
	if err != nil {
		t.Fatal(err)
	}
	text := string(out)
	if strings.Contains(text, "Core") || strings.Contains(text, "core") {
		t.Errorf("removed group still present:\n%s", text)
	}
	if !strings.Contains(text, "Apps() apps.Interface") || !strings.Contains(text, "internalinterfaces.SharedInformerFactory") {
		t.Errorf("kept group or embedded interface missing:\n%s", text)
	}
	if !strings.Contains(text, "ForResource") {
		t.Errorf("generic informer stub missing:\n%s", text)
	}
	if unused := unusedImports(parseOutput(t, out)); len(unused) != 0 {
		t.Errorf("unused imports left: %v", unused)
	}
}

func TestLeanInformerFactoryNamesMissingGroup(t *testing.T) {
	_, err := leanInformerFactory([]byte(factorySource), []string{"apps", "storage"})
	if err == nil || !strings.Contains(err.Error(), "storage") {
		t.Fatalf("want an error naming storage, got %v", err)
	}
}

const groupSource = `package resource

import (
	internalinterfaces "k8s.io/client-go/informers/internalinterfaces"
	v1 "k8s.io/client-go/informers/resource/v1"
	v1alpha3 "k8s.io/client-go/informers/resource/v1alpha3"
)

type Interface interface {
	// V1 doc
	V1() v1.Interface
	V1alpha3() v1alpha3.Interface
}

type group struct {
	factory internalinterfaces.SharedInformerFactory
}

func (g *group) V1() v1.Interface {
	return v1.New(g.factory)
}

func (g *group) V1alpha3() v1alpha3.Interface {
	return v1alpha3.New(g.factory)
}
`

func TestLeanInformerGroupKeepsListedVersions(t *testing.T) {
	out, err := leanInformerGroup([]byte(groupSource), "resource", []string{"v1"})
	if err != nil {
		t.Fatal(err)
	}
	text := string(out)
	if strings.Contains(text, "alpha3") {
		t.Errorf("removed version still present:\n%s", text)
	}
	if unused := unusedImports(parseOutput(t, out)); len(unused) != 0 {
		t.Errorf("unused imports left: %v", unused)
	}
}

func TestLeanInformerGroupNamesMissingVersion(t *testing.T) {
	_, err := leanInformerGroup([]byte(groupSource), "resource", []string{"v1", "v1beta2"})
	if err == nil || !strings.Contains(err.Error(), "v1beta2") || !strings.Contains(err.Error(), "resource") {
		t.Fatalf("want an error naming resource and v1beta2, got %v", err)
	}
}
