// Code generated by scripts/genresources from the served resources. DO NOT EDIT.

package rbac

import (
	external "k8s.io/api/rbac/v1"
	"k8s.io/apimachinery/pkg/util/runtime"
	"k8s.io/client-go/kubernetes/scheme"
	internal "k8s.io/kubernetes/pkg/apis/rbac/v1"
)

const GroupVersion = "rbac.authorization.k8s.io/v1"

func init() {
	runtime.Must(external.AddToScheme(scheme.Scheme))
	runtime.Must(internal.AddToScheme(scheme.Scheme))
}
