// Code generated by scripts/genresources from the served resources. DO NOT EDIT.

package openapi

import (
	_ "github.com/k8flare/k8flare/packages/apiserver-apps"
	_ "github.com/k8flare/k8flare/packages/apiserver-authentication"
	_ "github.com/k8flare/k8flare/packages/apiserver-authorization"
	_ "github.com/k8flare/k8flare/packages/apiserver-coordination"
	_ "github.com/k8flare/k8flare/packages/apiserver-core"
	_ "github.com/k8flare/k8flare/packages/apiserver-discovery"
	_ "github.com/k8flare/k8flare/packages/apiserver-node"
	_ "github.com/k8flare/k8flare/packages/apiserver-policy"
	_ "github.com/k8flare/k8flare/packages/apiserver-rbac"
	_ "github.com/k8flare/k8flare/packages/apiserver-resource"
	_ "github.com/k8flare/k8flare/packages/apiserver-storage"
)
