// Code generated by hack/genresources from github.com/k3s-io/kubernetes@v1.36.4-k3s1 api/discovery. DO NOT EDIT.

package apiserver

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"
)

var servedResources = []servedGroupVersion{
	{schema.GroupVersion{Group: "", Version: "v1"}, []metav1.APIResource{
		{Name: "configmaps", SingularName: "configmap", Namespaced: true, Kind: "ConfigMap", Verbs: metav1.Verbs{"create", "delete", "deletecollection", "get", "list", "patch", "update", "watch"}, ShortNames: []string{"cm"}, Categories: nil},
		{Name: "events", SingularName: "event", Namespaced: true, Kind: "Event", Verbs: metav1.Verbs{"create", "delete", "deletecollection", "get", "list", "patch", "update", "watch"}, ShortNames: []string{"ev"}, Categories: nil},
		{Name: "namespaces", SingularName: "namespace", Namespaced: false, Kind: "Namespace", Verbs: metav1.Verbs{"create", "delete", "get", "list", "patch", "update", "watch"}, ShortNames: []string{"ns"}, Categories: nil},
		{Name: "namespaces/status", SingularName: "", Namespaced: false, Kind: "Namespace", Verbs: metav1.Verbs{"get", "patch", "update"}, ShortNames: nil, Categories: nil},
		{Name: "nodes", SingularName: "node", Namespaced: false, Kind: "Node", Verbs: metav1.Verbs{"create", "delete", "deletecollection", "get", "list", "patch", "update", "watch"}, ShortNames: []string{"no"}, Categories: nil},
		{Name: "nodes/status", SingularName: "", Namespaced: false, Kind: "Node", Verbs: metav1.Verbs{"get", "patch", "update"}, ShortNames: nil, Categories: nil},
		{Name: "pods", SingularName: "pod", Namespaced: true, Kind: "Pod", Verbs: metav1.Verbs{"create", "delete", "deletecollection", "get", "list", "patch", "update", "watch"}, ShortNames: []string{"po"}, Categories: []string{"all"}},
		{Name: "pods/log", SingularName: "", Namespaced: true, Kind: "Pod", Verbs: metav1.Verbs{"get"}, ShortNames: nil, Categories: nil},
		{Name: "pods/status", SingularName: "", Namespaced: true, Kind: "Pod", Verbs: metav1.Verbs{"get", "patch", "update"}, ShortNames: nil, Categories: nil},
		{Name: "secrets", SingularName: "secret", Namespaced: true, Kind: "Secret", Verbs: metav1.Verbs{"create", "delete", "deletecollection", "get", "list", "patch", "update", "watch"}, ShortNames: nil, Categories: nil},
		{Name: "serviceaccounts", SingularName: "serviceaccount", Namespaced: true, Kind: "ServiceAccount", Verbs: metav1.Verbs{"create", "delete", "deletecollection", "get", "list", "patch", "update", "watch"}, ShortNames: []string{"sa"}, Categories: nil},
		{Name: "services", SingularName: "service", Namespaced: true, Kind: "Service", Verbs: metav1.Verbs{"create", "delete", "deletecollection", "get", "list", "patch", "update", "watch"}, ShortNames: []string{"svc"}, Categories: []string{"all"}},
		{Name: "services/status", SingularName: "", Namespaced: true, Kind: "Service", Verbs: metav1.Verbs{"get", "patch", "update"}, ShortNames: nil, Categories: nil},
	}},
	{schema.GroupVersion{Group: "coordination.k8s.io", Version: "v1"}, []metav1.APIResource{
		{Name: "leases", SingularName: "lease", Namespaced: true, Kind: "Lease", Verbs: metav1.Verbs{"create", "delete", "deletecollection", "get", "list", "patch", "update", "watch"}, ShortNames: nil, Categories: nil},
	}},
	{schema.GroupVersion{Group: "discovery.k8s.io", Version: "v1"}, []metav1.APIResource{
		{Name: "endpointslices", SingularName: "endpointslice", Namespaced: true, Kind: "EndpointSlice", Verbs: metav1.Verbs{"create", "delete", "deletecollection", "get", "list", "patch", "update", "watch"}, ShortNames: nil, Categories: nil},
	}},
	{schema.GroupVersion{Group: "node.k8s.io", Version: "v1"}, []metav1.APIResource{
		{Name: "runtimeclasses", SingularName: "runtimeclass", Namespaced: false, Kind: "RuntimeClass", Verbs: metav1.Verbs{"create", "delete", "deletecollection", "get", "list", "patch", "update", "watch"}, ShortNames: nil, Categories: nil},
	}},
	{schema.GroupVersion{Group: "storage.k8s.io", Version: "v1"}, []metav1.APIResource{
		{Name: "csidrivers", SingularName: "csidriver", Namespaced: false, Kind: "CSIDriver", Verbs: metav1.Verbs{"create", "delete", "deletecollection", "get", "list", "patch", "update", "watch"}, ShortNames: nil, Categories: nil},
		{Name: "csinodes", SingularName: "csinode", Namespaced: false, Kind: "CSINode", Verbs: metav1.Verbs{"create", "delete", "deletecollection", "get", "list", "patch", "update", "watch"}, ShortNames: nil, Categories: nil},
	}},
	{schema.GroupVersion{Group: "authentication.k8s.io", Version: "v1"}, []metav1.APIResource{
		{Name: "tokenreviews", SingularName: "tokenreview", Namespaced: false, Kind: "TokenReview", Verbs: metav1.Verbs{"create"}, ShortNames: nil, Categories: nil},
	}},
	{schema.GroupVersion{Group: "authorization.k8s.io", Version: "v1"}, []metav1.APIResource{
		{Name: "selfsubjectaccessreviews", SingularName: "selfsubjectaccessreview", Namespaced: false, Kind: "SelfSubjectAccessReview", Verbs: metav1.Verbs{"create"}, ShortNames: nil, Categories: nil},
		{Name: "subjectaccessreviews", SingularName: "subjectaccessreview", Namespaced: false, Kind: "SubjectAccessReview", Verbs: metav1.Verbs{"create"}, ShortNames: nil, Categories: nil},
	}},
}
