// Code generated by k8flare-gen. DO NOT EDIT.
package apiserver

// OpenAPIV3Discovery is the JSON body served at GET /openapi/v3 (see
// RegisterOpenAPIDiscovery, openapi.go): a {"paths": {...}} map from each
// served GroupVersion's OpenAPI v3 document path to its Static-Assets URL
// and content hash. Generated from the real per-group-version documents
// copied into workers/apiserver/assets/openapi/v3/ -- see
// cmd/k8flare-gen/openapi.go.
var OpenAPIV3Discovery = []byte(`{"paths":{"api/v1":{"serverRelativeURL":"/openapi/v3/api/v1?hash=a3cbb14c08e7"},"apis/apps/v1":{"serverRelativeURL":"/openapi/v3/apis/apps/v1?hash=4e190f85e4d9"},"apis/autoscaling/v2":{"serverRelativeURL":"/openapi/v3/apis/autoscaling/v2?hash=47726b03de58"},"apis/batch/v1":{"serverRelativeURL":"/openapi/v3/apis/batch/v1?hash=f39ccc48cf5d"},"apis/coordination.k8s.io/v1":{"serverRelativeURL":"/openapi/v3/apis/coordination.k8s.io/v1?hash=54b9a4143dbe"},"apis/discovery.k8s.io/v1":{"serverRelativeURL":"/openapi/v3/apis/discovery.k8s.io/v1?hash=29b42c9d7c94"},"apis/networking.k8s.io/v1":{"serverRelativeURL":"/openapi/v3/apis/networking.k8s.io/v1?hash=ea25fb66aae6"},"apis/node.k8s.io/v1":{"serverRelativeURL":"/openapi/v3/apis/node.k8s.io/v1?hash=e08ef6b735b0"},"apis/policy/v1":{"serverRelativeURL":"/openapi/v3/apis/policy/v1?hash=89af0b1d3257"},"apis/rbac.authorization.k8s.io/v1":{"serverRelativeURL":"/openapi/v3/apis/rbac.authorization.k8s.io/v1?hash=060632eb16c8"},"apis/resource.k8s.io/v1":{"serverRelativeURL":"/openapi/v3/apis/resource.k8s.io/v1?hash=db24d1cb2468"},"apis/storage.k8s.io/v1":{"serverRelativeURL":"/openapi/v3/apis/storage.k8s.io/v1?hash=b6599cea1616"}}}`)
