// Code generated by k8flare-gen. DO NOT EDIT.
package apiserver

// kubernetesMajor, kubernetesMinor, and kubernetesGitVersion mirror the
// k8s.io/kubernetes version pinned in go.mod (resolved via 'go list -m'),
// so GET /version's reported version can't silently drift out of sync with
// the actually-vendored API types the way a hand-maintained literal did
// (this project's oldest one hard-coded Minor "34" long after go.mod had
// moved on to 1.36 -- see docs/k8s-version-bump.md).
const (
	kubernetesMajor      = "1"
	kubernetesMinor      = "36"
	kubernetesGitVersion = "v1.36.4+k8flare"
)
