// Code generated by k8flare-gen. DO NOT EDIT.
package apiserver

import (
	"fmt"

	appsv1defaults "k8s.io/kubernetes/pkg/apis/apps/v1"
	batchv1defaults "k8s.io/kubernetes/pkg/apis/batch/v1"
	corev1defaults "k8s.io/kubernetes/pkg/apis/core/v1"
)

// registerVersionedDefaults registers every API group's real upstream
// versioned defaulting functions (k8s.io/kubernetes/pkg/apis/<group>/<version>)
// onto Scheme, so Scheme.Default(obj) (called from ApplyDefaults, defaults.go)
// applies them -- generated from apidef.Table's GroupVersions crossed with
// cmd/k8flare-gen/defaulters.go's defaulterPackage list; a GroupVersion with no
// known defaulters package (e.g. node.k8s.io/v1) is skipped.
func registerVersionedDefaults() error {
	if err := appsv1defaults.RegisterDefaults(Scheme); err != nil {
		return fmt.Errorf("register apps/v1 defaults: %w", err)
	}
	if err := batchv1defaults.RegisterDefaults(Scheme); err != nil {
		return fmt.Errorf("register batch/v1 defaults: %w", err)
	}
	if err := corev1defaults.RegisterDefaults(Scheme); err != nil {
		return fmt.Errorf("register v1 defaults: %w", err)
	}
	return nil
}
