// Code generated by scripts/genresources from the served resources. DO NOT EDIT.

package core

import (
	_ "embed"

	registry "github.com/k8flare/k8flare/packages/apiserver-registry"
	external "k8s.io/api/core/v1"
	"k8s.io/apimachinery/pkg/util/runtime"
	"k8s.io/client-go/kubernetes/scheme"
	internal "k8s.io/kubernetes/pkg/apis/core/v1"
)

const GroupVersion = "v1"

//go:embed openapi.json
var openAPIDefinitions []byte

func init() {
	runtime.Must(registry.UseOpenAPIDefinitions(openAPIDefinitions))
	runtime.Must(external.AddToScheme(scheme.Scheme))
	runtime.Must(internal.AddToScheme(scheme.Scheme))
}
