package main

import (
	"fmt"
	"strings"
)

// leanClientType describes one API type pkg/leanclient/gen must implement
// a client-go XInterface for. This table is this generator's own small
// hand-written source of truth (mirrors pkg/apiserver/apidef.Table's
// role for the apiserver side) -- see pkg/leanclient/leanclient.go's doc
// comment and pkg/clientgo-lean-overlays/README.md for why this
// package exists at all (client-go's own generated typed clients cost
// ~45MiB of linked GOOS=js/wasm code regardless of scheme scope).
//
// Limited to the 13 types this repo's real, unmodified upstream
// controllers (pkg/controller/{replicaset,deployment,daemon,job,cronjob,
// endpoint,endpointslice,nodeipam,nodelifecycle,tainteviction}), scheduler
// (pkg/scheduler), and every controller/scheduler's
// record.EventBroadcaster (client-go/tools/events, wired up right after
// Run()) actually construct clients/informers for (confirmed by grep, not
// guessed) -- adding a resource here requires a
// matching hand-curated interface-only extraction in
// pkg/clientgo-lean-overlays/kubernetes/typed/<group>/<version>/
// and pkg/clientgo-lean-overlays/applyconfigurations/<group>/<version>/
// first (see that directory's README.md), since the generated code below
// implements interfaces declared there, not upstream's unpruned ones.
type leanClientType struct {
	// Kind is the Go type name, e.g. "Pod".
	Kind string
	// Receiver is the unexported plural receiver name client-go's own
	// generated code uses for this type, e.g. "pods" -- kept identical so
	// this package's shape matches upstream's for anyone diffing them.
	Receiver string
	// Resource is the plural lowercase URL path segment, e.g. "pods".
	Resource string
	// Namespaced is false for cluster-scoped types (Node).
	Namespaced bool
	// HasUpdateStatus is whether this type's XInterface declares
	// UpdateStatus (client-gen omits it for types annotated
	// +genclient:noStatus upstream -- Endpoints, ControllerRevision,
	// EndpointSlice, Lease).
	HasUpdateStatus bool

	// APIPackageAlias/APIPackagePath: k8s.io/api/<group>/<version>, the
	// concrete object type's own package.
	APIPackageAlias string
	APIPackagePath  string
	// ApplyConfigPackageAlias/ApplyConfigPackagePath: this repo's pruned
	// pkg/clientgo-lean-overlays/applyconfigurations/<group>/<version>
	// mirror -- only ever referenced for Apply/ApplyStatus's parameter type
	// (see leanclient.go's doc comment for why a real implementation isn't
	// provided: Server-Side Apply is unused by every controller/scheduler
	// this repo enables).
	ApplyConfigPackageAlias string
	ApplyConfigPackagePath  string

	// ExtraImports/Extras: this type's XExpansion interface methods
	// (Pod's Bind/Evict*/GetLogs/ProxyGet, Node's PatchStatus, Service's
	// ProxyGet) plus any non-CRUD method the base XInterface itself
	// declares (ReplicaSet/Deployment's ApplyScale) -- a handful of
	// varied, one-off signatures too irregular for the uniform
	// writeLeanClientType template above, hand-written once here and
	// spliced verbatim into the generated file (still emitted by the
	// generator, still regenerated by `go run ./cmd/k8flare-gen`, just
	// not templated). Only Pod's Bind has a real implementation --
	// confirmed by grep, it's the only one this repo's real upstream
	// scheduler (pkg/scheduler/framework/plugins/defaultbinder) actually
	// calls. Every other method here is an intentional panic stub.
	ExtraImports []string
	Extras       string
}

// leanClientGroup is one client-go typed/<group>/<version> package: the
// GroupVersion's REST API path pieces, plus the types within it.
type leanClientGroup struct {
	// GoPackage is this generated file's own package suffix, e.g. "corev1".
	GoPackage string
	// APIPath is "/api" for the legacy core group, "/apis" for every other
	// group (matches client-go's own setConfigDefaults per group).
	APIPath string
	// GroupVersion is schema.GroupVersion's literal Go construction, e.g.
	// `schema.GroupVersion{Group: "", Version: "v1"}`.
	GroupVersion string
	// TypedPackageAlias/TypedPackagePath: this repo's pruned
	// pkg/clientgo-lean-overlays/kubernetes/typed/<group>/<version>
	// mirror, declaring the XInterface/XGetter this file implements.
	TypedPackageAlias string
	TypedPackagePath  string
	// GroupInterface is this group's aggregate interface name declared in
	// the typed package above, e.g. "CoreV1Interface".
	GroupInterface string
	// OtherGetterStubs: panic-stub methods for this group's Getters
	// *beyond* the types in Types below -- GroupInterface's full upstream
	// width (e.g. CoreV1Interface has 16 Getters; this repo's Clientset
	// implements 4 for real) requires every other Getter to exist on
	// *Client too, even though nothing calls them (confirmed by grep --
	// see leanclient.go's package doc comment on why the full width is
	// unavoidable once pkg/scheduler.New's aggregate
	// informers.SharedInformerFactory parameter is in the same binary).
	// Raw method source, spliced in by writeLeanClientGroupAggregate.
	OtherGetterStubs string

	Types []leanClientType
}

var leanClientGroups = []leanClientGroup{
	{
		GoPackage:         "corev1",
		APIPath:           "/api",
		GroupVersion:      `schema.GroupVersion{Group: "", Version: "v1"}`,
		TypedPackageAlias: "corev1client",
		TypedPackagePath:  "k8s.io/client-go/kubernetes/typed/core/v1",
		GroupInterface:    "CoreV1Interface",
		OtherGetterStubs:  coreV1OtherGetterStubs,
		Types: []leanClientType{
			{Kind: "Pod", Receiver: "pods", Resource: "pods", Namespaced: true, HasUpdateStatus: true,
				APIPackageAlias: "corev1", APIPackagePath: "k8s.io/api/core/v1",
				ApplyConfigPackageAlias: "applyconfigurationscorev1", ApplyConfigPackagePath: "k8s.io/client-go/applyconfigurations/core/v1",
				ExtraImports: []string{
					`"encoding/json"`,
					`policyv1 "k8s.io/api/policy/v1"`,
					`policyv1beta1 "k8s.io/api/policy/v1beta1"`,
				},
				Extras: podExtras,
			},
			{Kind: "Node", Receiver: "nodes", Resource: "nodes", Namespaced: false, HasUpdateStatus: true,
				APIPackageAlias: "corev1", APIPackagePath: "k8s.io/api/core/v1",
				ApplyConfigPackageAlias: "applyconfigurationscorev1", ApplyConfigPackagePath: "k8s.io/client-go/applyconfigurations/core/v1",
				Extras: nodeExtras,
			},
			{Kind: "Service", Receiver: "services", Resource: "services", Namespaced: true, HasUpdateStatus: true,
				APIPackageAlias: "corev1", APIPackagePath: "k8s.io/api/core/v1",
				ApplyConfigPackageAlias: "applyconfigurationscorev1", ApplyConfigPackagePath: "k8s.io/client-go/applyconfigurations/core/v1",
				Extras: serviceExtras,
			},
			{Kind: "Endpoints", Receiver: "endpoints", Resource: "endpoints", Namespaced: true, HasUpdateStatus: false,
				APIPackageAlias: "corev1", APIPackagePath: "k8s.io/api/core/v1",
				ApplyConfigPackageAlias: "applyconfigurationscorev1", ApplyConfigPackagePath: "k8s.io/client-go/applyconfigurations/core/v1"},
			// PersistentVolumeClaim: the real statefulset controller
			// (pkg/controller/statefulset) creates/reads/deletes each
			// replica's PVC directly from volumeClaimTemplates -- see
			// docs/general-purpose-k8s-plan.md's Phase 3 StatefulSet entry.
			// PersistentVolumeClaimExpansion is empty upstream (no extras).
			{Kind: "PersistentVolumeClaim", Receiver: "persistentVolumeClaims", Resource: "persistentvolumeclaims", Namespaced: true, HasUpdateStatus: true,
				APIPackageAlias: "corev1", APIPackagePath: "k8s.io/api/core/v1",
				ApplyConfigPackageAlias: "applyconfigurationscorev1", ApplyConfigPackagePath: "k8s.io/client-go/applyconfigurations/core/v1"},
			// PersistentVolume: the real kube-scheduler's event handlers
			// register a PV informer, whose ListAndWatch crashed on the old
			// panic stub during the schedwidth bring-up (2026-07-10). PV is
			// a real apidef.Table resource this apiserver serves.
			// PersistentVolumeExpansion is empty upstream (no extras).
			{Kind: "PersistentVolume", Receiver: "persistentVolumes", Resource: "persistentvolumes", Namespaced: false, HasUpdateStatus: true,
				APIPackageAlias: "corev1", APIPackagePath: "k8s.io/api/core/v1",
				ApplyConfigPackageAlias: "applyconfigurationscorev1", ApplyConfigPackagePath: "k8s.io/client-go/applyconfigurations/core/v1"},
			// Namespace: PodTopologySpread/InterPodAffinity's namespace
			// lister -- same schedwidth bring-up finding as
			// PersistentVolume above (2026-07-10). Finalize is a panic
			// stub (namespaceExtras), never called by the scheduler.
			{Kind: "Namespace", Receiver: "namespaces", Resource: "namespaces", Namespaced: false, HasUpdateStatus: true,
				APIPackageAlias: "corev1", APIPackagePath: "k8s.io/api/core/v1",
				ApplyConfigPackageAlias: "applyconfigurationscorev1", ApplyConfigPackagePath: "k8s.io/client-go/applyconfigurations/core/v1",
				Extras: namespaceExtras,
			},
			// ReplicationController: PodTopologySpread's setListers builds
			// an RC lister/informer unconditionally -- same schedwidth
			// bring-up finding as PersistentVolume/Namespace (2026-07-10).
			// RC is a real apidef.Table resource. GetScale/UpdateScale are
			// panic stubs (replicationControllerExtras).
			{Kind: "ReplicationController", Receiver: "replicationControllers", Resource: "replicationcontrollers", Namespaced: true, HasUpdateStatus: true,
				APIPackageAlias: "corev1", APIPackagePath: "k8s.io/api/core/v1",
				ApplyConfigPackageAlias: "applyconfigurationscorev1", ApplyConfigPackagePath: "k8s.io/client-go/applyconfigurations/core/v1",
				ExtraImports: []string{
					`autoscalingv1 "k8s.io/api/autoscaling/v1"`,
				},
				Extras: replicationControllerExtras,
			},
			{Kind: "Event", Receiver: "events", Resource: "events", Namespaced: true, HasUpdateStatus: false,
				APIPackageAlias: "corev1", APIPackagePath: "k8s.io/api/core/v1",
				ApplyConfigPackageAlias: "applyconfigurationscorev1", ApplyConfigPackagePath: "k8s.io/client-go/applyconfigurations/core/v1",
				ExtraImports: []string{
					`"k8s.io/apimachinery/pkg/fields"`,
					`"k8s.io/apimachinery/pkg/runtime"`,
				},
				Extras: eventExtras,
			},
		},
	},
	{
		GoPackage:         "appsv1",
		APIPath:           "/apis",
		GroupVersion:      `schema.GroupVersion{Group: "apps", Version: "v1"}`,
		TypedPackageAlias: "appsv1client",
		TypedPackagePath:  "k8s.io/client-go/kubernetes/typed/apps/v1",
		GroupInterface:    "AppsV1Interface",
		Types: []leanClientType{
			{Kind: "ReplicaSet", Receiver: "replicaSets", Resource: "replicasets", Namespaced: true, HasUpdateStatus: true,
				APIPackageAlias: "appsv1", APIPackagePath: "k8s.io/api/apps/v1",
				ApplyConfigPackageAlias: "applyconfigurationsappsv1", ApplyConfigPackagePath: "k8s.io/client-go/applyconfigurations/apps/v1",
				ExtraImports: []string{
					`autoscalingv1 "k8s.io/api/autoscaling/v1"`,
					`applyconfigurationsautoscalingv1 "k8s.io/client-go/applyconfigurations/autoscaling/v1"`,
				},
				Extras: applyScaleExtras("replicaSets", "ReplicaSets"),
			},
			{Kind: "Deployment", Receiver: "deployments", Resource: "deployments", Namespaced: true, HasUpdateStatus: true,
				APIPackageAlias: "appsv1", APIPackagePath: "k8s.io/api/apps/v1",
				ApplyConfigPackageAlias: "applyconfigurationsappsv1", ApplyConfigPackagePath: "k8s.io/client-go/applyconfigurations/apps/v1",
				ExtraImports: []string{
					`autoscalingv1 "k8s.io/api/autoscaling/v1"`,
					`applyconfigurationsautoscalingv1 "k8s.io/client-go/applyconfigurations/autoscaling/v1"`,
				},
				Extras: applyScaleExtras("deployments", "Deployments"),
			},
			{Kind: "DaemonSet", Receiver: "daemonSets", Resource: "daemonsets", Namespaced: true, HasUpdateStatus: true,
				APIPackageAlias: "appsv1", APIPackagePath: "k8s.io/api/apps/v1",
				ApplyConfigPackageAlias: "applyconfigurationsappsv1", ApplyConfigPackagePath: "k8s.io/client-go/applyconfigurations/apps/v1"},
			{Kind: "ControllerRevision", Receiver: "controllerRevisions", Resource: "controllerrevisions", Namespaced: true, HasUpdateStatus: false,
				APIPackageAlias: "appsv1", APIPackagePath: "k8s.io/api/apps/v1",
				ApplyConfigPackageAlias: "applyconfigurationsappsv1", ApplyConfigPackagePath: "k8s.io/client-go/applyconfigurations/apps/v1"},
			{Kind: "StatefulSet", Receiver: "statefulSets", Resource: "statefulsets", Namespaced: true, HasUpdateStatus: true,
				APIPackageAlias: "appsv1", APIPackagePath: "k8s.io/api/apps/v1",
				ApplyConfigPackageAlias: "applyconfigurationsappsv1", ApplyConfigPackagePath: "k8s.io/client-go/applyconfigurations/apps/v1",
				ExtraImports: []string{
					`autoscalingv1 "k8s.io/api/autoscaling/v1"`,
					`applyconfigurationsautoscalingv1 "k8s.io/client-go/applyconfigurations/autoscaling/v1"`,
				},
				Extras: applyScaleExtras("statefulSets", "StatefulSets"),
			},
		},
	},
	{
		GoPackage:         "batchv1",
		APIPath:           "/apis",
		GroupVersion:      `schema.GroupVersion{Group: "batch", Version: "v1"}`,
		TypedPackageAlias: "batchv1client",
		TypedPackagePath:  "k8s.io/client-go/kubernetes/typed/batch/v1",
		GroupInterface:    "BatchV1Interface",
		Types: []leanClientType{
			{Kind: "Job", Receiver: "jobs", Resource: "jobs", Namespaced: true, HasUpdateStatus: true,
				APIPackageAlias: "batchv1", APIPackagePath: "k8s.io/api/batch/v1",
				ApplyConfigPackageAlias: "applyconfigurationsbatchv1", ApplyConfigPackagePath: "k8s.io/client-go/applyconfigurations/batch/v1"},
			{Kind: "CronJob", Receiver: "cronJobs", Resource: "cronjobs", Namespaced: true, HasUpdateStatus: true,
				APIPackageAlias: "batchv1", APIPackagePath: "k8s.io/api/batch/v1",
				ApplyConfigPackageAlias: "applyconfigurationsbatchv1", ApplyConfigPackagePath: "k8s.io/client-go/applyconfigurations/batch/v1"},
		},
	},
	{
		GoPackage:         "discoveryv1",
		APIPath:           "/apis",
		GroupVersion:      `schema.GroupVersion{Group: "discovery.k8s.io", Version: "v1"}`,
		TypedPackageAlias: "discoveryv1client",
		TypedPackagePath:  "k8s.io/client-go/kubernetes/typed/discovery/v1",
		GroupInterface:    "DiscoveryV1Interface",
		Types: []leanClientType{
			{Kind: "EndpointSlice", Receiver: "endpointSlices", Resource: "endpointslices", Namespaced: true, HasUpdateStatus: false,
				APIPackageAlias: "discoveryv1", APIPackagePath: "k8s.io/api/discovery/v1",
				ApplyConfigPackageAlias: "applyconfigurationsdiscoveryv1", ApplyConfigPackagePath: "k8s.io/client-go/applyconfigurations/discovery/v1"},
		},
	},
	{
		GoPackage:         "coordinationv1",
		APIPath:           "/apis",
		GroupVersion:      `schema.GroupVersion{Group: "coordination.k8s.io", Version: "v1"}`,
		TypedPackageAlias: "coordinationv1client",
		TypedPackagePath:  "k8s.io/client-go/kubernetes/typed/coordination/v1",
		GroupInterface:    "CoordinationV1Interface",
		Types: []leanClientType{
			{Kind: "Lease", Receiver: "leases", Resource: "leases", Namespaced: true, HasUpdateStatus: false,
				APIPackageAlias: "coordinationv1", APIPackagePath: "k8s.io/api/coordination/v1",
				ApplyConfigPackageAlias: "applyconfigurationscoordinationv1", ApplyConfigPackagePath: "k8s.io/client-go/applyconfigurations/coordination/v1"},
		},
	},
	{
		// storagev1 exists for the real, unmodified upstream kube-scheduler
		// (pkg/scheduler.New unconditionally builds a nodevolumelimits.
		// NewCSIManager(informerFactory.Storage().V1().CSINodes().Lister())
		// -- confirmed by reading scheduler.go, not gated behind any
		// feature flag), not for this repo's controllers -- see
		// docs/platform-verification.md's S8 kube-scheduler-wasm-fork
		// entry. VolumeAttributesClasses is upstream's StorageV1Interface's
		// only Getter beyond the 5 implemented here; confirmed unused by
		// grep, permanent panic stub like every other *OtherGetterStubs.
		GoPackage:         "storagev1",
		APIPath:           "/apis",
		GroupVersion:      `schema.GroupVersion{Group: "storage.k8s.io", Version: "v1"}`,
		TypedPackageAlias: "storagev1client",
		TypedPackagePath:  "k8s.io/client-go/kubernetes/typed/storage/v1",
		GroupInterface:    "StorageV1Interface",
		OtherGetterStubs:  storageV1OtherGetterStubs,
		Types: []leanClientType{
			{Kind: "CSIDriver", Receiver: "cSIDrivers", Resource: "csidrivers", Namespaced: false, HasUpdateStatus: false,
				APIPackageAlias: "storagev1", APIPackagePath: "k8s.io/api/storage/v1",
				ApplyConfigPackageAlias: "applyconfigurationsstoragev1", ApplyConfigPackagePath: "k8s.io/client-go/applyconfigurations/storage/v1"},
			{Kind: "CSINode", Receiver: "cSINodes", Resource: "csinodes", Namespaced: false, HasUpdateStatus: false,
				APIPackageAlias: "storagev1", APIPackagePath: "k8s.io/api/storage/v1",
				ApplyConfigPackageAlias: "applyconfigurationsstoragev1", ApplyConfigPackagePath: "k8s.io/client-go/applyconfigurations/storage/v1"},
			{Kind: "CSIStorageCapacity", Receiver: "cSIStorageCapacities", Resource: "csistoragecapacities", Namespaced: true, HasUpdateStatus: false,
				APIPackageAlias: "storagev1", APIPackagePath: "k8s.io/api/storage/v1",
				ApplyConfigPackageAlias: "applyconfigurationsstoragev1", ApplyConfigPackagePath: "k8s.io/client-go/applyconfigurations/storage/v1"},
			{Kind: "StorageClass", Receiver: "storageClasses", Resource: "storageclasses", Namespaced: false, HasUpdateStatus: false,
				APIPackageAlias: "storagev1", APIPackagePath: "k8s.io/api/storage/v1",
				ApplyConfigPackageAlias: "applyconfigurationsstoragev1", ApplyConfigPackagePath: "k8s.io/client-go/applyconfigurations/storage/v1"},
			{Kind: "VolumeAttachment", Receiver: "volumeAttachments", Resource: "volumeattachments", Namespaced: false, HasUpdateStatus: true,
				APIPackageAlias: "storagev1", APIPackagePath: "k8s.io/api/storage/v1",
				ApplyConfigPackageAlias: "applyconfigurationsstoragev1", ApplyConfigPackagePath: "k8s.io/client-go/applyconfigurations/storage/v1"},
		},
	},
	{
		// resourcev1 exists for the real, unmodified upstream kube-scheduler's
		// DynamicResources/DRA machinery: DynamicResourceAllocation is GA
		// and LockToDefault:true in v1.36.2-k3s1 (verified by reading
		// pkg/features/kube_features.go, not assumed), so scheduler.go's DRA
		// construction block always runs, unconditionally constructing
		// ResourceClaim/ResourceSlice/DeviceClass informers -- see
		// docs/platform-verification.md's S8 kube-scheduler-wasm-fork
		// entry. ResourceClaimTemplates is upstream's ResourceV1Interface's
		// only Getter beyond the 3 implemented here; confirmed unused by
		// grep (the scheduler never expands templates -- that's the
		// resourceclaim controller's job, not scheduled by this repo's
		// wasm KCM), permanent panic stub.
		GoPackage:         "resourcev1",
		APIPath:           "/apis",
		GroupVersion:      `schema.GroupVersion{Group: "resource.k8s.io", Version: "v1"}`,
		TypedPackageAlias: "resourcev1client",
		TypedPackagePath:  "k8s.io/client-go/kubernetes/typed/resource/v1",
		GroupInterface:    "ResourceV1Interface",
		OtherGetterStubs:  resourceV1OtherGetterStubs,
		Types: []leanClientType{
			{Kind: "DeviceClass", Receiver: "deviceClasses", Resource: "deviceclasses", Namespaced: false, HasUpdateStatus: false,
				APIPackageAlias: "resourcev1", APIPackagePath: "k8s.io/api/resource/v1",
				ApplyConfigPackageAlias: "applyconfigurationsresourcev1", ApplyConfigPackagePath: "k8s.io/client-go/applyconfigurations/resource/v1"},
			{Kind: "ResourceClaim", Receiver: "resourceClaims", Resource: "resourceclaims", Namespaced: true, HasUpdateStatus: true,
				APIPackageAlias: "resourcev1", APIPackagePath: "k8s.io/api/resource/v1",
				ApplyConfigPackageAlias: "applyconfigurationsresourcev1", ApplyConfigPackagePath: "k8s.io/client-go/applyconfigurations/resource/v1"},
			{Kind: "ResourceSlice", Receiver: "resourceSlices", Resource: "resourceslices", Namespaced: false, HasUpdateStatus: false,
				APIPackageAlias: "resourcev1", APIPackagePath: "k8s.io/api/resource/v1",
				ApplyConfigPackageAlias: "applyconfigurationsresourcev1", ApplyConfigPackagePath: "k8s.io/client-go/applyconfigurations/resource/v1"},
		},
	},
	{
		// policyv1 exists for the real, unmodified upstream kube-scheduler:
		// framework/preemption/{preemption,podgrouppreemption,executor}.go
		// unconditionally build a PodDisruptionBudget lister
		// (DefaultPreemption is not in sched.go's disabled-plugins list --
		// confirmed by reading pkg/controllers/sched/sched.go). Evictions
		// is upstream's PolicyV1Interface's only other Getter; confirmed
		// unused (the scheduler never evicts Pods itself -- that's
		// kubectl drain/the eviction API's client side), permanent panic
		// stub.
		GoPackage:         "policyv1",
		APIPath:           "/apis",
		GroupVersion:      `schema.GroupVersion{Group: "policy", Version: "v1"}`,
		TypedPackageAlias: "policyv1client",
		TypedPackagePath:  "k8s.io/client-go/kubernetes/typed/policy/v1",
		GroupInterface:    "PolicyV1Interface",
		OtherGetterStubs:  policyV1OtherGetterStubs,
		Types: []leanClientType{
			{Kind: "PodDisruptionBudget", Receiver: "podDisruptionBudgets", Resource: "poddisruptionbudgets", Namespaced: true, HasUpdateStatus: true,
				APIPackageAlias: "policyv1", APIPackagePath: "k8s.io/api/policy/v1",
				ApplyConfigPackageAlias: "applyconfigurationspolicyv1", ApplyConfigPackagePath: "k8s.io/client-go/applyconfigurations/policy/v1"},
		},
	},
}

// policyV1OtherGetterStubs panic-stubs PolicyV1Interface's one Getter
// beyond PodDisruptionBudgets (Evictions) -- confirmed unused by the
// real, unmodified upstream scheduler this repo embeds.
const policyV1OtherGetterStubs = `
func (c *Client) Evictions(namespace string) policyv1client.EvictionInterface {
	panic("leanclient: Evictions not implemented (unused by this repo's scheduler)")
}
`

// storageV1OtherGetterStubs panic-stubs StorageV1Interface's one Getter
// beyond CSIDrivers/CSINodes/CSIStorageCapacities/StorageClasses/
// VolumeAttachments (VolumeAttributesClasses) -- confirmed unused by the
// real, unmodified upstream scheduler this repo embeds.
const storageV1OtherGetterStubs = `
func (c *Client) VolumeAttributesClasses() storagev1client.VolumeAttributesClassInterface {
	panic("leanclient: VolumeAttributesClasses not implemented (unused by this repo's scheduler)")
}
`

// resourceV1OtherGetterStubs panic-stubs ResourceV1Interface's one Getter
// beyond DeviceClasses/ResourceClaims/ResourceSlices
// (ResourceClaimTemplates) -- confirmed unused by the real, unmodified
// upstream scheduler this repo embeds.
const resourceV1OtherGetterStubs = `
func (c *Client) ResourceClaimTemplates(namespace string) resourcev1client.ResourceClaimTemplateInterface {
	panic("leanclient: ResourceClaimTemplates not implemented (unused by this repo's scheduler)")
}
`

// podExtras implements PodExpansion. Bind is the only one of these
// coreV1OtherGetterStubs panic-stubs CoreV1Interface's remaining Getters
// beyond Pods/Nodes/Services/Endpoints/Events/PersistentVolumeClaims/
// PersistentVolumes/Namespaces/ReplicationControllers
// (ComponentStatuses, ConfigMaps, LimitRanges, PodTemplates,
// ResourceQuotas, Secrets, ServiceAccounts) -- confirmed unused by every
// controller/scheduler this repo enables. Events was moved out of this
// list and into Types below: unlike these, it *is* called -- every
// controller/scheduler's record.EventBroadcaster (wired up right after
// Run()) calls client.CoreV1().Events(ns) via
// client-go/tools/events.NewEventBroadcasterAdapter, so a panic stub here
// crashed the GOOS=js wasm process immediately on startup (see
// spikes/s14-loader-external-fetch/FINDINGS.md Part 5). PersistentVolumeClaims
// moved out the same way once the statefulset controller (which reads/writes
// PVCs directly, no informer beyond factory.PersistentVolumeClaims()) was
// enabled -- see docs/general-purpose-k8s-plan.md's Phase 3 StatefulSet entry.
// PersistentVolumes moved out the same way for the schedwidth scheduler
// (2026-07-10): the real scheduler's event handlers register a PV
// informer, whose ListAndWatch called this accessor and crashed the
// first sched dynamic-worker boot -- and PV is a real apidef.Table
// resource this apiserver serves, so a real client is correct, not a
// widened stub.
const coreV1OtherGetterStubs = `
func (c *Client) ComponentStatuses() corev1client.ComponentStatusInterface {
	panic("leanclient: ComponentStatuses not implemented (unused by this repo's controllers/scheduler)")
}
func (c *Client) ConfigMaps(namespace string) corev1client.ConfigMapInterface {
	panic("leanclient: ConfigMaps not implemented (unused by this repo's controllers/scheduler)")
}
func (c *Client) LimitRanges(namespace string) corev1client.LimitRangeInterface {
	panic("leanclient: LimitRanges not implemented (unused by this repo's controllers/scheduler)")
}
func (c *Client) PodTemplates(namespace string) corev1client.PodTemplateInterface {
	panic("leanclient: PodTemplates not implemented (unused by this repo's controllers/scheduler)")
}
func (c *Client) ResourceQuotas(namespace string) corev1client.ResourceQuotaInterface {
	panic("leanclient: ResourceQuotas not implemented (unused by this repo's controllers/scheduler)")
}
func (c *Client) Secrets(namespace string) corev1client.SecretInterface {
	panic("leanclient: Secrets not implemented (unused by this repo's controllers/scheduler)")
}
func (c *Client) ServiceAccounts(namespace string) corev1client.ServiceAccountInterface {
	panic("leanclient: ServiceAccounts not implemented (unused by this repo's controllers/scheduler)")
}
`

// AppsV1Interface's Getter set is now fully covered by Types below
// (ReplicaSets/Deployments/DaemonSets/ControllerRevisions/StatefulSets) --
// no OtherGetterStubs remain for this group.

// methods this repo's real, unmodified upstream scheduler ever calls
// (pkg/scheduler/framework/plugins/defaultbinder -- confirmed by grep):
// it POSTs the binding to the pod's binding subresource, the same shape
// as upstream's own gentype-based implementation, just via DoRaw+json
// instead of a runtime.Scheme-backed codec (see pkg/leanclient's doc
// comment for why). Evict/EvictV1/EvictV1beta1/GetLogs/ProxyGet are
// intentional panic stubs -- unused by every controller/scheduler this
// repo enables.
const podExtras = `
func (c *pods) Bind(ctx context.Context, binding *corev1.Binding, opts metav1.CreateOptions) error {
	// Stamp TypeMeta: plain encoding/json (unlike client-go's codec path)
	// otherwise emits a body without kind/apiVersion, which this
	// apiserver's strict decoder 400s ("Object 'Kind' is missing") --
	// found live 2026-07-10 when the first in-Worker scheduler's
	// DefaultBinder got 400 on every pods/binding POST; same fix as
	// leanclient.Delete's DeleteOptions stamping.
	binding.TypeMeta = metav1.TypeMeta{APIVersion: "v1", Kind: "Binding"}
	body, err := json.Marshal(binding)
	if err != nil {
		return err
	}
	req := c.client.Post().Namespace(c.ns).Resource("pods").Name(binding.Name).SubResource("binding").Body(body)
	for _, dr := range opts.DryRun {
		req = req.Param("dryRun", dr)
	}
	if opts.FieldManager != "" {
		req = req.Param("fieldManager", opts.FieldManager)
	}
	_, err = req.DoRaw(ctx)
	return err
}

func (c *pods) Evict(ctx context.Context, eviction *policyv1beta1.Eviction) error {
	panic("leanclient: Pods.Evict not implemented (unused by this repo's controllers/scheduler)")
}

func (c *pods) EvictV1(ctx context.Context, eviction *policyv1.Eviction) error {
	panic("leanclient: Pods.EvictV1 not implemented (unused by this repo's controllers/scheduler)")
}

func (c *pods) EvictV1beta1(ctx context.Context, eviction *policyv1beta1.Eviction) error {
	panic("leanclient: Pods.EvictV1beta1 not implemented (unused by this repo's controllers/scheduler)")
}

func (c *pods) GetLogs(name string, opts *corev1.PodLogOptions) *restclient.Request {
	panic("leanclient: Pods.GetLogs not implemented (unused by this repo's controllers/scheduler)")
}

func (c *pods) ProxyGet(scheme, name, port, path string, params map[string]string) restclient.ResponseWrapper {
	panic("leanclient: Pods.ProxyGet not implemented (unused by this repo's controllers/scheduler)")
}

func (c *pods) UpdateEphemeralContainers(ctx context.Context, podName string, pod *corev1.Pod, opts metav1.UpdateOptions) (*corev1.Pod, error) {
	panic("leanclient: Pods.UpdateEphemeralContainers not implemented (unused by this repo's controllers/scheduler)")
}

func (c *pods) UpdateResize(ctx context.Context, podName string, pod *corev1.Pod, opts metav1.UpdateOptions) (*corev1.Pod, error) {
	panic("leanclient: Pods.UpdateResize not implemented (unused by this repo's controllers/scheduler)")
}
`

// nodeExtras implements NodeExpansion (PatchStatus) -- an intentional
// panic stub, unused by this repo's controllers/scheduler.
const nodeExtras = `
func (c *nodes) PatchStatus(ctx context.Context, nodeName string, data []byte) (*corev1.Node, error) {
	panic("leanclient: Nodes.PatchStatus not implemented (unused by this repo's controllers/scheduler)")
}
`

// namespaceExtras implements NamespaceExpansion (Finalize) -- an
// intentional panic stub: the scheduler only LISTS/WATCHES namespaces
// (PodTopologySpread/InterPodAffinity's namespace lister), never
// finalizes one (that's the namespace-lifecycle controller's job, which
// this repo's apiserver handles itself).
const namespaceExtras = `
func (c *namespaces) Finalize(ctx context.Context, item *corev1.Namespace, opts metav1.UpdateOptions) (*corev1.Namespace, error) {
	panic("leanclient: Namespaces.Finalize not implemented (unused by this repo's controllers/scheduler)")
}
`

// replicationControllerExtras panic-stubs RC's scale methods (declared
// on the base interface, not an Expansion): the scheduler
// (PodTopologySpread's setListers) only LISTS ReplicationControllers.
const replicationControllerExtras = `
func (c *replicationControllers) GetScale(ctx context.Context, replicationControllerName string, options metav1.GetOptions) (*autoscalingv1.Scale, error) {
	panic("leanclient: ReplicationControllers.GetScale not implemented (unused by this repo's controllers/scheduler)")
}
func (c *replicationControllers) UpdateScale(ctx context.Context, replicationControllerName string, scale *autoscalingv1.Scale, opts metav1.UpdateOptions) (*autoscalingv1.Scale, error) {
	panic("leanclient: ReplicationControllers.UpdateScale not implemented (unused by this repo's controllers/scheduler)")
}
`

// serviceExtras implements ServiceExpansion (ProxyGet) -- an intentional
// panic stub, unused by this repo's controllers/scheduler.
const serviceExtras = `
func (c *services) ProxyGet(scheme, name, port, path string, params map[string]string) restclient.ResponseWrapper {
	panic("leanclient: Services.ProxyGet not implemented (unused by this repo's controllers/scheduler)")
}
`

// eventExtras implements EventExpansion for real: unlike this file's other
// XExpansion stubs, Events *is* on this repo's actual call path --
// client-go/tools/events.EventBroadcasterAdapter (wired up by every
// controller/scheduler right after Run(), confirmed by grep) POSTs/PUTs/
// PATCHes through exactly these three "WithEventNamespace" methods via its
// EventSinkImpl, so a panic stub here crashed the GOOS=js wasm process on
// startup (see spikes/s14-loader-external-fetch/FINDINGS.md Part 5). The
// deprecated non-context variants and GetFieldSelector are trivial
// pass-throughs, implemented for real too since they cost nothing extra.
// Search/SearchWithContext remain intentional panic stubs: EventSinkImpl
// never calls them (confirmed by grep of client-go/tools/events), and
// nothing else in this repo's controllers/scheduler does either.
const eventExtras = `
// eventNamespace mirrors upstream client-go's WithEventNamespace
// semantics (event_expansion.go's NamespaceIfScoped): the request targets
// the *event's own* namespace, not the client's. The distinction matters
// because record.EventBroadcaster builds its sink as Events("") -- with
// c.ns alone, every write went to the cluster-scoped /api/v1/events path
// and silently failed (found live: zero Events stored while the real
// controllers were demonstrably reconciling).
func (c *events) eventNamespace(eventNS string) *events {
	if eventNS == "" || eventNS == c.ns {
		return c
	}
	return NewEvents(c.client, eventNS)
}

func (c *events) CreateWithEventNamespace(event *corev1.Event) (*corev1.Event, error) {
	return c.CreateWithEventNamespaceWithContext(context.Background(), event)
}

func (c *events) CreateWithEventNamespaceWithContext(ctx context.Context, event *corev1.Event) (*corev1.Event, error) {
	return c.eventNamespace(event.Namespace).Create(ctx, event, metav1.CreateOptions{})
}

func (c *events) UpdateWithEventNamespace(event *corev1.Event) (*corev1.Event, error) {
	return c.UpdateWithEventNamespaceWithContext(context.Background(), event)
}

func (c *events) UpdateWithEventNamespaceWithContext(ctx context.Context, event *corev1.Event) (*corev1.Event, error) {
	return c.eventNamespace(event.Namespace).Update(ctx, event, metav1.UpdateOptions{})
}

func (c *events) PatchWithEventNamespace(incompleteEvent *corev1.Event, data []byte) (*corev1.Event, error) {
	return c.PatchWithEventNamespaceWithContext(context.Background(), incompleteEvent, data)
}

func (c *events) PatchWithEventNamespaceWithContext(ctx context.Context, incompleteEvent *corev1.Event, data []byte) (*corev1.Event, error) {
	return c.eventNamespace(incompleteEvent.Namespace).Patch(ctx, incompleteEvent.Name, types.StrategicMergePatchType, data, metav1.PatchOptions{})
}

func (c *events) Search(scheme *runtime.Scheme, objOrRef runtime.Object) (*corev1.EventList, error) {
	panic("leanclient: Events.Search not implemented (unused by this repo's controllers/scheduler)")
}

func (c *events) SearchWithContext(ctx context.Context, scheme *runtime.Scheme, objOrRef runtime.Object) (*corev1.EventList, error) {
	panic("leanclient: Events.SearchWithContext not implemented (unused by this repo's controllers/scheduler)")
}

func (c *events) GetFieldSelector(involvedObjectName, involvedObjectNamespace, involvedObjectKind, involvedObjectUID *string) fields.Selector {
	field := fields.Set{}
	if involvedObjectName != nil {
		field["involvedObject.name"] = *involvedObjectName
	}
	if involvedObjectNamespace != nil {
		field["involvedObject.namespace"] = *involvedObjectNamespace
	}
	if involvedObjectKind != nil {
		field["involvedObject.kind"] = *involvedObjectKind
	}
	if involvedObjectUID != nil {
		field["involvedObject.uid"] = *involvedObjectUID
	}
	return field.AsSelector()
}
`

// applyScaleExtras implements ReplicaSetInterface/DeploymentInterface's
// ApplyScale (a base interface method, not an XExpansion one -- part of
// the /scale subresource's Server-Side Apply path) -- an intentional
// panic stub: this repo's apiserver doesn't implement the /scale
// subresource at all yet (see README.md), so no controller can call this
// regardless of Server-Side Apply.
func applyScaleExtras(receiver, methodOwner string) string {
	return fmt.Sprintf(`
func (c *%s) GetScale(ctx context.Context, name string, options metav1.GetOptions) (*autoscalingv1.Scale, error) {
	panic("leanclient: %s.GetScale not implemented (unused by this repo's controllers/scheduler)")
}

func (c *%s) UpdateScale(ctx context.Context, name string, scale *autoscalingv1.Scale, opts metav1.UpdateOptions) (*autoscalingv1.Scale, error) {
	panic("leanclient: %s.UpdateScale not implemented (unused by this repo's controllers/scheduler)")
}

func (c *%s) ApplyScale(ctx context.Context, name string, scale *applyconfigurationsautoscalingv1.ScaleApplyConfiguration, opts metav1.ApplyOptions) (*autoscalingv1.Scale, error) {
	panic("leanclient: %s.ApplyScale not implemented (unused by this repo's controllers/scheduler)")
}
`, receiver, methodOwner, receiver, methodOwner, receiver, methodOwner)
}

// genLeanClient writes pkg/leanclient/gen/<group><version>.go per
// leanClientGroups entry: one struct + constructor per type, implementing
// its client-go XInterface's CRUD/Watch methods via pkg/leanclient's
// verb/watch helpers (never through a runtime.Scheme -- see
// pkg/leanclient/leanclient.go's doc comment), plus Apply/ApplyStatus
// panic stubs (required by the interface; never called -- zero
// Server-Side Apply use in this repo's controllers/scheduler, confirmed
// by grep). Each type's Extras field (above) supplies its remaining,
// non-uniform XExpansion/base-interface methods.
func genLeanClient(root string) error {
	for _, group := range leanClientGroups {
		var b strings.Builder
		fmt.Fprintf(&b, "//go:build js && wasm\n\n// %s\n\npackage %s\n\n", generatedHeader, group.GoPackage)

		b.WriteString("import (\n")
		b.WriteString("\t\"context\"\n\n")
		b.WriteString("\tmetav1 \"k8s.io/apimachinery/pkg/apis/meta/v1\"\n")
		b.WriteString("\t\"k8s.io/apimachinery/pkg/runtime/schema\"\n")
		b.WriteString("\t\"k8s.io/apimachinery/pkg/types\"\n")
		b.WriteString("\tapimachinerywatch \"k8s.io/apimachinery/pkg/watch\"\n")
		b.WriteString("\trestclient \"k8s.io/client-go/rest\"\n\n")
		fmt.Fprintf(&b, "\t%s %q\n", group.TypedPackageAlias, group.TypedPackagePath)
		b.WriteString("\n\t\"github.com/k8flare/k8flare/pkg/leanclient\"\n")
		seenAPIPkg := map[string]bool{}
		seenApplyPkg := map[string]bool{}
		for _, t := range group.Types {
			if !seenAPIPkg[t.APIPackagePath] {
				fmt.Fprintf(&b, "\t%s %q\n", t.APIPackageAlias, t.APIPackagePath)
				seenAPIPkg[t.APIPackagePath] = true
			}
		}
		for _, t := range group.Types {
			if !seenApplyPkg[t.ApplyConfigPackagePath] {
				fmt.Fprintf(&b, "\t%s %q\n", t.ApplyConfigPackageAlias, t.ApplyConfigPackagePath)
				seenApplyPkg[t.ApplyConfigPackagePath] = true
			}
		}
		seenExtra := map[string]bool{}
		for _, t := range group.Types {
			for _, imp := range t.ExtraImports {
				if !seenExtra[imp] {
					fmt.Fprintf(&b, "\t%s\n", imp)
					seenExtra[imp] = true
				}
			}
		}
		b.WriteString(")\n\n")

		fmt.Fprintf(&b, "// RESTClientFor builds this group's *rest.RESTClient, sharing cfg's Transport.\n")
		fmt.Fprintf(&b, "func RESTClientFor(cfg *restclient.Config) (*restclient.RESTClient, error) {\n")
		fmt.Fprintf(&b, "\treturn leanclient.RESTClientFor(cfg, %q, %s)\n", group.APIPath, group.GroupVersion)
		b.WriteString("}\n\n")

		writeLeanClientGroupAggregate(&b, group)

		for _, t := range group.Types {
			writeLeanClientType(&b, t, group.TypedPackageAlias, group.GroupVersion)
		}

		outPath := fmt.Sprintf("%s/pkg/leanclient/gen/%s/%s.go", root, group.GoPackage, group.GoPackage)
		if err := writeGoFile(outPath, []byte(b.String())); err != nil {
			return fmt.Errorf("%s: %w", group.GoPackage, err)
		}
	}
	return nil
}

func capitalize(s string) string {
	if s == "" {
		return s
	}
	return strings.ToUpper(s[:1]) + s[1:]
}

// writeLeanClientGroupAggregate emits Client, the group-level struct
// satisfying e.g. corev1client.CoreV1Interface (RESTClient() + one
// XsGetter method per type) by delegating each XsGetter method to the
// matching NewXs constructor below.
func writeLeanClientGroupAggregate(b *strings.Builder, group leanClientGroup) {
	b.WriteString("type Client struct {\n\trc restclient.Interface\n}\n\n")
	fmt.Fprintf(b, "var _ %s.%s = (*Client)(nil)\n\n", group.TypedPackageAlias, group.GroupInterface)

	b.WriteString("func New(cfg *restclient.Config) (*Client, error) {\n")
	b.WriteString("\trc, err := RESTClientFor(cfg)\n\tif err != nil {\n\t\treturn nil, err\n\t}\n")
	b.WriteString("\treturn &Client{rc: rc}, nil\n}\n\n")

	b.WriteString("func (c *Client) RESTClient() restclient.Interface { return c.rc }\n\n")

	for _, t := range group.Types {
		// The XsGetter method name matches t.Receiver capitalized, not
		// simply Kind+"s" -- Endpoints is already plural (EndpointsGetter.
		// Endpoints, not "Endpointss"), so this must follow client-go's
		// own generated method name (== this repo's Receiver, chosen to
		// match it) rather than mechanically appending "s" to Kind.
		getterMethod := capitalize(t.Receiver)
		fmt.Fprintf(b, "func (c *Client) %s(", getterMethod)
		if t.Namespaced {
			fmt.Fprintf(b, "namespace string) %s.%sInterface {\n", group.TypedPackageAlias, t.Kind)
			fmt.Fprintf(b, "\treturn New%s(c.rc, namespace)\n}\n\n", getterMethod)
		} else {
			fmt.Fprintf(b, ") %s.%sInterface {\n", group.TypedPackageAlias, t.Kind)
			fmt.Fprintf(b, "\treturn New%s(c.rc)\n}\n\n", getterMethod)
		}
	}

	if group.OtherGetterStubs != "" {
		b.WriteString(group.OtherGetterStubs)
		b.WriteString("\n")
	}
}

func writeLeanClientType(b *strings.Builder, t leanClientType, typedPackageAlias, groupVersion string) {
	obj := t.APIPackageAlias + "." + t.Kind
	list := obj + "List"
	apply := t.ApplyConfigPackageAlias + "." + t.Kind + "ApplyConfiguration"
	// gvk is a literal schema.GroupVersionKind construction, spliced into
	// each Create/Update/UpdateStatus call below so leanclient.Create et
	// al. can stamp Kind/APIVersion onto the object before marshaling --
	// see pkg/leanclient/verbs.go's setTypeMeta doc comment for why this
	// is required (the k8flare apiserver's decoder 400s without it).
	gvk := fmt.Sprintf("%s.WithKind(%q)", groupVersion, t.Kind)

	fmt.Fprintf(b, "type %s struct {\n\tclient restclient.Interface\n\tns string\n}\n\n", t.Receiver)

	// Compile-time interface satisfaction check: if a k8s.io/client-go
	// bump adds/changes a method on this type's XInterface (declared in
	// the pruned pkg/clientgo-lean-overlays mirror), this fails
	// go build here instead of failing silently at runtime (same
	// reasoning as pkg/apiserver/apidef.Table's New/NewList closures).
	fmt.Fprintf(b, "var _ %s.%sInterface = (*%s)(nil)\n\n", typedPackageAlias, t.Kind, t.Receiver)

	nsArg := ""
	nsField := `""`
	if t.Namespaced {
		nsArg = "ns string"
		nsField = "ns"
	}
	fmt.Fprintf(b, "func New%s(c restclient.Interface", capitalize(t.Receiver))
	if nsArg != "" {
		fmt.Fprintf(b, ", %s", nsArg)
	}
	fmt.Fprintf(b, ") *%s {\n\treturn &%s{client: c, ns: %s}\n}\n\n", t.Receiver, t.Receiver, nsField)

	fmt.Fprintf(b, "func (c *%s) Create(ctx context.Context, obj *%s, opts metav1.CreateOptions) (*%s, error) {\n", t.Receiver, obj, obj)
	fmt.Fprintf(b, "\treturn leanclient.Create(ctx, c.client, %q, c.ns, obj, %s, opts)\n}\n\n", t.Resource, gvk)

	fmt.Fprintf(b, "func (c *%s) Update(ctx context.Context, obj *%s, opts metav1.UpdateOptions) (*%s, error) {\n", t.Receiver, obj, obj)
	fmt.Fprintf(b, "\treturn leanclient.Update(ctx, c.client, %q, c.ns, obj.Name, obj, %s, opts)\n}\n\n", t.Resource, gvk)

	if t.HasUpdateStatus {
		fmt.Fprintf(b, "func (c *%s) UpdateStatus(ctx context.Context, obj *%s, opts metav1.UpdateOptions) (*%s, error) {\n", t.Receiver, obj, obj)
		fmt.Fprintf(b, "\treturn leanclient.UpdateSubresource(ctx, c.client, %q, c.ns, obj.Name, \"status\", obj, %s, opts)\n}\n\n", t.Resource, gvk)
	}

	fmt.Fprintf(b, "func (c *%s) Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error {\n", t.Receiver)
	fmt.Fprintf(b, "\treturn leanclient.Delete(ctx, c.client, %q, c.ns, name, opts)\n}\n\n", t.Resource)

	fmt.Fprintf(b, "func (c *%s) DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error {\n", t.Receiver)
	fmt.Fprintf(b, "\treturn leanclient.DeleteCollection(ctx, c.client, %q, c.ns, opts, listOpts)\n}\n\n", t.Resource)

	fmt.Fprintf(b, "func (c *%s) Get(ctx context.Context, name string, opts metav1.GetOptions) (*%s, error) {\n", t.Receiver, obj)
	fmt.Fprintf(b, "\treturn leanclient.Get[%s](ctx, c.client, %q, c.ns, name, opts)\n}\n\n", obj, t.Resource)

	fmt.Fprintf(b, "func (c *%s) List(ctx context.Context, opts metav1.ListOptions) (*%s, error) {\n", t.Receiver, list)
	fmt.Fprintf(b, "\treturn leanclient.List[%s](ctx, c.client, %q, c.ns, opts)\n}\n\n", list, t.Resource)

	fmt.Fprintf(b, "func (c *%s) Watch(ctx context.Context, opts metav1.ListOptions) (apimachinerywatch.Interface, error) {\n", t.Receiver)
	fmt.Fprintf(b, "\treturn leanclient.Watch(ctx, c.client, %q, c.ns, opts, func() *%s { return &%s{} })\n}\n\n", t.Resource, obj, obj)

	fmt.Fprintf(b, "func (c *%s) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (*%s, error) {\n", t.Receiver, obj)
	fmt.Fprintf(b, "\treturn leanclient.Patch[%s](ctx, c.client, %q, c.ns, name, pt, data, opts, subresources...)\n}\n\n", obj, t.Resource)

	fmt.Fprintf(b, "func (c *%s) Apply(ctx context.Context, obj *%s, opts metav1.ApplyOptions) (*%s, error) {\n", t.Receiver, apply, obj)
	fmt.Fprintf(b, "\tpanic(%q)\n}\n\n", "leanclient: Server-Side Apply not implemented (unused by this repo's controllers/scheduler)")

	if t.HasUpdateStatus {
		fmt.Fprintf(b, "func (c *%s) ApplyStatus(ctx context.Context, obj *%s, opts metav1.ApplyOptions) (*%s, error) {\n", t.Receiver, apply, obj)
		fmt.Fprintf(b, "\tpanic(%q)\n}\n\n", "leanclient: Server-Side Apply not implemented (unused by this repo's controllers/scheduler)")
	}

	if t.Extras != "" {
		b.WriteString(t.Extras)
		b.WriteString("\n")
	}
}
