// Command k8flare-gen regenerates every derived artifact from
// pkg/apiserver/apidef.Table and go.mod's k8s.io/kubernetes pin:
//
//   - pkg/apiserver/zz_generated_defaulters.go: registers every API group's
//     real upstream versioned defaulting functions onto Scheme.
//   - pkg/apiserver/zz_generated_version.go: the Major/Minor/GitVersion GET
//     /version reports, read from the pinned k8s.io/kubernetes module
//     version instead of a hand-maintained literal.
//   - packages/k8flare-worker/src/k8s/gen/resource-kinds.gen.ts: the resource-plural ->
//     Kind lookup table the gateway/watch layer uses.
//   - packages/k8flare-worker/assets/openapi/**: the real upstream OpenAPI v2/v3
//     documents for every group-version in apidef.Table, served as Static
//     Assets so `kubectl apply` works without --validate=false.
//
// Run this after editing pkg/apiserver/apidef/table.go or bumping
// k8s.io/kubernetes in go.mod, then `git diff --exit-code` to confirm
// nothing drifted (also enforced in CI -- see .github/workflows/ci.yml and
// docs/k8s-version-bump.md).
package main

import (
	"fmt"
	"os"
	"path/filepath"
)

// generatedHeader is prepended (in a language-appropriate comment form) to
// every file this tool writes. pkg/apiserver/apidef and .claude/hooks/gen-guard.sh
// both key off the literal phrase "Code generated ... DO NOT EDIT" -- keep
// this exact wording if it's ever changed.
const generatedHeader = "Code generated by k8flare-gen. DO NOT EDIT."

func main() {
	if err := run(); err != nil {
		fmt.Fprintln(os.Stderr, "k8flare-gen:", err)
		os.Exit(1)
	}
}

func run() error {
	root, err := projectRoot()
	if err != nil {
		return err
	}

	steps := []struct {
		name string
		fn   func(root string) error
	}{
		{"defaulters", genDefaulters},
		{"version", genVersion},
		{"resource-kinds", genResourceKinds},
		{"openapi", genOpenAPI},
		{"discovery-assets", genDiscoveryAssets},
		{"leanclient", genLeanClient},
	}
	for _, step := range steps {
		if err := step.fn(root); err != nil {
			return fmt.Errorf("%s: %w", step.name, err)
		}
		fmt.Fprintln(os.Stderr, "k8flare-gen:", step.name, "ok")
	}
	return nil
}

// projectRoot walks up from the current directory to find the repo root
// (identified by go.mod), the same way pkg/apiserver/apiserver_test.go's
// findProjectRoot does, so this tool works regardless of the caller's cwd.
func projectRoot() (string, error) {
	dir, err := os.Getwd()
	if err != nil {
		return "", err
	}
	for {
		if _, err := os.Stat(filepath.Join(dir, "go.mod")); err == nil {
			return dir, nil
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			return "", fmt.Errorf("go.mod not found above %s", dir)
		}
		dir = parent
	}
}
