package main

import (
	"bytes"
	"fmt"
	"go/format"
	"sort"
	"strings"
)

const header = "// Code generated by scripts/genwake from the informers the shard controller constructors are handed. DO NOT EDIT.\n\n"

func renderNeeds(n needs) ([]byte, error) {
	var out bytes.Buffer
	out.WriteString(header)
	out.WriteString("package workloads\n\nvar controllerNeeds = map[string][]string{\n")
	var controllers []string
	for c := range n {
		controllers = append(controllers, c)
	}
	sort.Strings(controllers)
	for _, c := range controllers {
		fmt.Fprintf(&out, "\t%q: {%s},\n", c, quoted(n.sorted(c)))
	}
	out.WriteString("}\n")
	return format.Source(out.Bytes())
}

func renderPrefixesTest(prefixes []string) ([]byte, error) {
	var out bytes.Buffer
	out.WriteString(header)
	out.WriteString("package workloads\n\nvar generatedWorkloadPrefixes = []string{\n")
	for _, p := range prefixes {
		fmt.Fprintf(&out, "\t%q,\n", p)
	}
	out.WriteString("}\n")
	return format.Source(out.Bytes())
}

func renderPrefixesTS(prefixes []string) []byte {
	var out bytes.Buffer
	out.WriteString(header)
	out.WriteString("export const WORKLOAD_PREFIXES = [\n")
	for _, p := range prefixes {
		fmt.Fprintf(&out, "  %q,\n", p)
	}
	out.WriteString("];\n")
	return out.Bytes()
}

func quoted(items []string) string {
	q := make([]string, len(items))
	for i, item := range items {
		q[i] = fmt.Sprintf("%q", item)
	}
	return strings.Join(q, ", ")
}
