// Code generated by scripts/genversion from github.com/k3s-io/kubernetes@v1.36.4-k3s1 and go.mod. DO NOT EDIT.

package kubeversion

const (
	Major      = "1"
	Minor      = "36"
	GitVersion = "v1.36.4+k8flare"
	GoVersion  = "go1.26"
)
