//go:build js && wasm

// Command resident is the S8 spike's instance-reuse variant (S5). It is paired
// with a hand-written JS glue (../resident/build/worker.mjs, generated by this
// package's build step and then hand-edited) that instantiates the WASM module
// only once per isolate and dispatches every subsequent fetch() into the same
// running Go program, instead of creating a fresh WebAssembly.Instance per request.
//
// It depends on a forked copy of github.com/syumai/workers (../vendor/syumai-workers-fork)
// with one change in handler_js.go: the package-level doneCh is now closed at
// most once (sync.Once), instead of once per completed request/stream. See
// FINDINGS.md for why that change is required.
//
// main() never calls workers.Serve (which blocks on the now-mostly-inert
// Done() channel); it calls ServeNonBlock+Ready and then parks forever, so the
// program's lifetime is independent of any single request's stream lifecycle.
package main

import (
	"bufio"
	"fmt"
	"math/rand"
	"net/http"
	"runtime"
	"sync"
	"sync/atomic"
	"time"

	"github.com/syumai/workers"
	"github.com/syumai/workers/cloudflare"
)

var (
	instanceID = fmt.Sprintf("resident-%08x", rand.Uint32())
	startedAt  = time.Now()

	requestsServed int64 // incremented once per dispatched request; proves reuse when > 1 across separate curl calls
	mainTicker     int64 // incremented by a goroutine started once in main(), before any request ever arrives
	onDemandTicker int64 // incremented by a goroutine started from inside a /start-worker request handler

	waitUntilCalls     int64
	waitUntilCompleted int64

	startOnce sync.Once

	// outboundReads/outboundErr exercise the *client* side (Go issuing a
	// long-lived outbound GET and reading a streamed response line by
	// line), which is the shape a real informer/watch loop actually uses.
	// This is distinct from streamHandler, which exercises the *server*
	// side (Go writing a streamed response). See /watch-sim.
	outboundReads int64
	outboundErrMu sync.Mutex
	outboundErr   string
	watchSimOnce  sync.Once
)

func statusHandler(w http.ResponseWriter, r *http.Request) {
	n := atomic.AddInt64(&requestsServed, 1)
	outboundErrMu.Lock()
	oErr := outboundErr
	outboundErrMu.Unlock()
	w.Header().Set("Content-Type", "application/json")
	fmt.Fprintf(w, `{"variant":"resident","instance_id":%q,"goroutines":%d,"uptime_s":%.3f,"requests_served":%d,"main_ticker":%d,"on_demand_ticker":%d,"wait_until_calls":%d,"wait_until_completed":%d,"outbound_reads":%d,"outbound_err":%q}`,
		instanceID, runtime.NumGoroutine(), time.Since(startedAt).Seconds(), n,
		atomic.LoadInt64(&mainTicker), atomic.LoadInt64(&onDemandTicker),
		atomic.LoadInt64(&waitUntilCalls), atomic.LoadInt64(&waitUntilCompleted),
		atomic.LoadInt64(&outboundReads), oErr)
}

// watchSimHandler starts a background goroutine that issues its own
// long-lived outbound GET to this same worker's /stream endpoint and reads
// it line by line -- i.e. the Go program acting as an HTTP *client*
// consuming a watch, the same shape kube-controller-manager's informers
// use. The handler itself returns immediately (like a "start the
// controller" call would), so whether outbound_reads keeps advancing in
// /status afterwards tells us whether an outbound watch keeps a reused
// instance's scheduler pumped the same way an inbound open response does.
func watchSimHandler(w http.ResponseWriter, r *http.Request) {
	atomic.AddInt64(&requestsServed, 1)
	started := false
	watchSimOnce.Do(func() {
		started = true
		host := r.Host
		go func() {
			resp, err := http.Get("http://" + host + "/stream")
			if err != nil {
				outboundErrMu.Lock()
				outboundErr = "Get: " + err.Error()
				outboundErrMu.Unlock()
				return
			}
			defer resp.Body.Close()
			scanner := bufio.NewScanner(resp.Body)
			for scanner.Scan() {
				atomic.AddInt64(&outboundReads, 1)
			}
			if err := scanner.Err(); err != nil {
				outboundErrMu.Lock()
				outboundErr = "Scan: " + err.Error()
				outboundErrMu.Unlock()
			}
		}()
	})
	w.Header().Set("Content-Type", "application/json")
	fmt.Fprintf(w, `{"started_this_call":%v}`, started)
}

// startWorkerHandler simulates "start a controller/informer on first watch",
// i.e. a goroutine spawned from *inside* a request handler (not main) that
// must keep running after this handler returns and across later, unrelated
// requests dispatched to the same reused instance.
func startWorkerHandler(w http.ResponseWriter, r *http.Request) {
	atomic.AddInt64(&requestsServed, 1)
	started := false
	startOnce.Do(func() {
		started = true
		go func() {
			t := time.NewTicker(2 * time.Second)
			defer t.Stop()
			for range t.C {
				atomic.AddInt64(&onDemandTicker, 1)
			}
		}()
	})
	w.Header().Set("Content-Type", "application/json")
	fmt.Fprintf(w, `{"started_this_call":%v}`, started)
}

// waitUntilHandler calls cloudflare.WaitUntil, which internally reads a
// package-level JS context captured once at Go-init time (i.e. from whichever
// request happened to trigger the one-and-only WebAssembly.Instance
// creation). On every request after the first on a reused instance, this is
// stale: it is a *different* HTTP request's ExecutionContext object, from
// workerd's point of view. This handler reports whether the call
// panicked so we can see exactly when/how that surfaces.
func waitUntilHandler(w http.ResponseWriter, r *http.Request) {
	n := atomic.AddInt64(&waitUntilCalls, 1)
	result := "ok"
	func() {
		defer func() {
			if rec := recover(); rec != nil {
				result = fmt.Sprintf("panic: %v", rec)
			}
		}()
		cloudflare.WaitUntil(func() {
			atomic.AddInt64(&waitUntilCompleted, 1)
		})
	}()
	w.Header().Set("Content-Type", "application/json")
	fmt.Fprintf(w, `{"call_number":%d,"result":%q}`, n, result)
}

func streamHandler(w http.ResponseWriter, r *http.Request) {
	atomic.AddInt64(&requestsServed, 1)
	w.Header().Set("Content-Type", "text/plain")
	w.Header().Set("Cache-Control", "no-store")

	start := time.Now()
	seq := 0
	ticker := time.NewTicker(2 * time.Second)
	defer ticker.Stop()
	for range ticker.C {
		seq++
		line := fmt.Sprintf("seq=%d instance=%s goroutines=%d elapsed=%s main_ticker=%d on_demand_ticker=%d\n",
			seq, instanceID, runtime.NumGoroutine(), time.Since(start).Truncate(time.Second),
			atomic.LoadInt64(&mainTicker), atomic.LoadInt64(&onDemandTicker))
		if _, err := fmt.Fprint(w, line); err != nil {
			return
		}
		if f, ok := w.(http.Flusher); ok {
			f.Flush()
		}
	}
}

func main() {
	mux := http.NewServeMux()
	mux.HandleFunc("/status", statusHandler)
	mux.HandleFunc("/stream", streamHandler)
	mux.HandleFunc("/start-worker", startWorkerHandler)
	mux.HandleFunc("/waituntil", waitUntilHandler)
	mux.HandleFunc("/watch-sim", watchSimHandler)
	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprintf(w, "s8 spike resident variant instance=%s\n", instanceID)
	})

	workers.ServeNonBlock(mux)
	workers.Ready()

	// Started exactly once, in main(), before any request has ever been
	// dispatched. If this counter is > 0 by the time a /status call
	// happens seconds after startup with zero requests in between, the
	// goroutine kept running with no request in flight at all.
	go func() {
		t := time.NewTicker(2 * time.Second)
		defer t.Stop()
		for range t.C {
			atomic.AddInt64(&mainTicker, 1)
		}
	}()

	select {} // park forever; do not depend on any single request's Done().
}
