apiVersion: v1
kind: ServiceAccount
metadata:
  name: k8flare-node-proxy
  namespace: kube-system
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: k8flare-node-proxy
  namespace: kube-system
  labels:
    k8s-app: k8flare-node-proxy
spec:
  revisionHistoryLimit: 0
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  selector:
    matchLabels:
      k8s-app: k8flare-node-proxy
  template:
    metadata:
      labels:
        k8s-app: k8flare-node-proxy
    spec:
      priorityClassName: system-node-critical
      serviceAccountName: k8flare-node-proxy
      hostNetwork: true
      dnsPolicy: Default
      tolerations:
        - operator: Exists
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/os
                    operator: In
                    values: ["linux"]
                  - key: k8flare.com/agent
                    operator: DoesNotExist
      containers:
      - name: node-proxy
        image: "ghcr.io/k8flare/node-proxy:latest"
        imagePullPolicy: IfNotPresent
        env:
        - name: GOMEMLIMIT
          value: 40MiB
        resources:
          requests:
            cpu: 10m
            memory: 16Mi
          limits:
            memory: 64Mi
        securityContext:
          runAsUser: 0
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop: ["ALL"]
          seccompProfile:
            type: RuntimeDefault
        readinessProbe:
          tcpSocket:
            port: 6443
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 6443
          initialDelaySeconds: 30
          periodSeconds: 20
        volumeMounts:
        - name: kubeconfig
          mountPath: /var/lib/rancher/k3s/agent/kubeproxy.kubeconfig
          readOnly: true
        - name: server-ca
          mountPath: /var/lib/rancher/k3s/agent/server-ca.crt
          readOnly: true
      volumes:
      - name: kubeconfig
        hostPath:
          path: /var/lib/rancher/k3s/agent/kubeproxy.kubeconfig
          type: File
      - name: server-ca
        hostPath:
          path: /var/lib/rancher/k3s/agent/server-ca.crt
          type: File
