// Code generated by scripts/genresources from the served resources. DO NOT EDIT.

package autoscaling

import (
	externalv2 "k8s.io/api/autoscaling/v2"
	externalv1 "k8s.io/api/autoscaling/v1"
	"k8s.io/apimachinery/pkg/util/runtime"
	"k8s.io/client-go/kubernetes/scheme"
	internalv2 "k8s.io/kubernetes/pkg/apis/autoscaling/v2"
	internalv1 "k8s.io/kubernetes/pkg/apis/autoscaling/v1"
)

const GroupVersion = "autoscaling/v2"

func init() {
	runtime.Must(externalv2.AddToScheme(scheme.Scheme))
	runtime.Must(internalv2.AddToScheme(scheme.Scheme))
	runtime.Must(externalv1.AddToScheme(scheme.Scheme))
	runtime.Must(internalv1.AddToScheme(scheme.Scheme))
}
