// Command genresources writes packages/apiserver-registry/zz_generated_resources.go from
// the discovery documents shipped with the pinned Kubernetes module
// (api/discovery/*.json), filtered to the resources this apiserver serves.
// Names, kinds, verbs, short names and categories therefore come from
// upstream, and a version bump that changes them shows up as a diff.
package main

import (
	"fmt"
	"github.com/k8flare/k8flare/scripts/internal/upstream"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

func main() {
	root, err := upstream.RepoRoot()
	check(err)
	dir, err := upstream.ModuleDir()
	check(err)
	var out strings.Builder
	out.WriteString("// Code generated by scripts/genresources from " + upstream.Module + "@" + upstream.Version + " api/discovery. DO NOT EDIT.\n\n")
	out.WriteString("package registry\n\nimport (\n\tmetav1 \"k8s.io/apimachinery/pkg/apis/meta/v1\"\n\t\"k8s.io/apimachinery/pkg/runtime/schema\"\n)\n\n")
	out.WriteString("// Served is the API surface, filtered from upstream's discovery documents.\nvar Served = []ServedGroupVersion{\n")
	for _, s := range upstream.Served {
		list, err := upstream.LoadDiscovery(dir, s.GV)
		check(err)
		byName := map[string]upstream.APIResource{}
		for _, r := range list.Resources {
			byName[r.Name] = r
		}
		group, ver := "", s.GV
		if i := strings.Index(s.GV, "/"); i >= 0 {
			group, ver = s.GV[:i], s.GV[i+1:]
		}
		fmt.Fprintf(&out, "\t{GV: schema.GroupVersion{Group: %q, Version: %q}, Resources: []metav1.APIResource{\n", group, ver)
		var names []string
		for _, name := range s.Resources {
			names = append(names, name)
			if _, ok := byName[name+"/status"]; ok && !strings.Contains(name, "/") {
				names = append(names, name+"/status")
			}
		}
		sort.Strings(names)
		for _, name := range names {
			r, ok := byName[name]
			if !ok {
				check(fmt.Errorf("%s: %s is not in upstream discovery", s.GV, name))
			}
			fmt.Fprintf(&out, "\t\t{Name: %q, SingularName: %q, Namespaced: %v, Kind: %q, Verbs: %s, ShortNames: %s, Categories: %s},\n",
				r.Name, r.SingularName, r.Namespaced, r.Kind, goStrings("metav1.Verbs", r.Verbs), goStrings("[]string", r.ShortNames), goStrings("[]string", r.Categories))
		}
		out.WriteString("\t}},\n")
	}
	out.WriteString("}\n")
	target := filepath.Join(root, "packages/apiserver-registry/zz_generated_resources.go")
	check(os.WriteFile(target, []byte(out.String()), 0o644))
	fmt.Println("genresources: wrote", target)
}

func goStrings(typ string, values []string) string {
	if len(values) == 0 {
		return "nil"
	}
	quoted := make([]string, len(values))
	for i, v := range values {
		quoted[i] = fmt.Sprintf("%q", v)
	}
	return typ + "{" + strings.Join(quoted, ", ") + "}"
}

func check(err error) {
	if err != nil {
		fmt.Fprintln(os.Stderr, "genresources:", err)
		os.Exit(1)
	}
}
