// Command genversion writes packages/kubeversion/zz_generated_version.go from
// the Kubernetes version pinned in scripts/internal/upstream/versions.mod and
// the go directive of the root go.mod, so the version this apiserver reports
// follows the mirrored source instead of a literal.
package main

import (
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"strings"

	"github.com/k8flare/k8flare/scripts/internal/upstream"
	"golang.org/x/mod/modfile"
	"golang.org/x/mod/semver"
)

const buildMetadata = "+k8flare"

type info struct {
	Major      string
	Minor      string
	GitVersion string
	GoVersion  string
}

func derive(kubernetesVersion, goDirective string) (info, error) {
	if !semver.IsValid(kubernetesVersion) {
		return info{}, fmt.Errorf("%s@%s is not a semantic version", upstream.Module, kubernetesVersion)
	}
	major, minor, ok := strings.Cut(strings.TrimPrefix(semver.MajorMinor(kubernetesVersion), "v"), ".")
	if !ok {
		return info{}, fmt.Errorf("%s has no major.minor", kubernetesVersion)
	}
	goParts := strings.Split(goDirective, ".")
	if len(goParts) < 2 {
		return info{}, fmt.Errorf("go.mod go directive %q has no major.minor", goDirective)
	}
	return info{
		Major:      major,
		Minor:      minor,
		GitVersion: strings.TrimSuffix(kubernetesVersion, semver.Prerelease(kubernetesVersion)) + buildMetadata,
		GoVersion:  "go" + goParts[0] + "." + goParts[1],
	}, nil
}

func render(source string, v info) ([]byte, error) {
	var out strings.Builder
	fmt.Fprintf(&out, "// Code generated by scripts/genversion from %s and go.mod. DO NOT EDIT.\n\npackage kubeversion\n\n", source)
	fmt.Fprintf(&out, "const (\n\tMajor = %q\n\tMinor = %q\n\tGitVersion = %q\n\tGoVersion = %q\n)\n", v.Major, v.Minor, v.GitVersion, v.GoVersion)
	return format.Source([]byte(out.String()))
}

func main() {
	root, err := upstream.RepoRoot()
	check(err)
	data, err := os.ReadFile(filepath.Join(root, "go.mod"))
	check(err)
	gomod, err := modfile.ParseLax("go.mod", data, nil)
	check(err)
	if gomod.Go == nil {
		check(fmt.Errorf("go.mod has no go directive"))
	}
	v, err := derive(upstream.Version, gomod.Go.Version)
	check(err)
	out, err := render(upstream.Module+"@"+upstream.Version, v)
	check(err)
	target := filepath.Join(root, "packages/kubeversion/zz_generated_version.go")
	check(os.MkdirAll(filepath.Dir(target), 0o755))
	check(os.WriteFile(target, out, 0o644))
	fmt.Println("genversion: wrote", target)
}

func check(err error) {
	if err != nil {
		fmt.Fprintln(os.Stderr, "genversion:", err)
		os.Exit(1)
	}
}
