package main

import (
	"strings"
	"testing"
)

func TestDerive(t *testing.T) {
	got, err := derive("v1.36.4-k3s1", "1.26.7")
	if err != nil {
		t.Fatal(err)
	}
	want := info{Major: "1", Minor: "36", GitVersion: "v1.36.4+k8flare", GoVersion: "go1.26"}
	if got != want {
		t.Fatalf("got %+v want %+v", got, want)
	}
}

func TestDeriveRejectsInvalidVersions(t *testing.T) {
	if _, err := derive("master", "1.26.7"); err == nil || !strings.Contains(err.Error(), "master") {
		t.Fatalf("kubernetes version: %v", err)
	}
	if _, err := derive("v1.36.4-k3s1", "go"); err == nil || !strings.Contains(err.Error(), "go") {
		t.Fatalf("go directive: %v", err)
	}
}

func TestRenderFormatsConstants(t *testing.T) {
	out, err := render("example.com/k@v1.2.3", info{Major: "1", Minor: "2", GitVersion: "v1.2.3+k8flare", GoVersion: "go1.26"})
	if err != nil {
		t.Fatal(err)
	}
	for _, want := range []string{
		"// Code generated by scripts/genversion from example.com/k@v1.2.3 and go.mod. DO NOT EDIT.",
		"package kubeversion",
		`Major      = "1"`,
		`Minor      = "2"`,
		`GitVersion = "v1.2.3+k8flare"`,
		`GoVersion  = "go1.26"`,
	} {
		if !strings.Contains(string(out), want) {
			t.Fatalf("missing %q in\n%s", want, out)
		}
	}
}
