// Code generated by scripts/genresources from github.com/k3s-io/kubernetes@v1.36.4-k3s1 api/discovery. DO NOT EDIT.

package registry

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"
)

// Served is the API surface, filtered from upstream's discovery documents.
var Served = []ServedGroupVersion{
	{GV: schema.GroupVersion{Group: "", Version: "v1"}, Resources: []metav1.APIResource{
		{Name: "configmaps", SingularName: "configmap", Namespaced: true, Kind: "ConfigMap", Verbs: metav1.Verbs{"create", "delete", "deletecollection", "get", "list", "patch", "update", "watch"}, ShortNames: []string{"cm"}, Categories: nil},
		{Name: "events", SingularName: "event", Namespaced: true, Kind: "Event", Verbs: metav1.Verbs{"create", "delete", "deletecollection", "get", "list", "patch", "update", "watch"}, ShortNames: []string{"ev"}, Categories: nil},
		{Name: "namespaces", SingularName: "namespace", Namespaced: false, Kind: "Namespace", Verbs: metav1.Verbs{"create", "delete", "get", "list", "patch", "update", "watch"}, ShortNames: []string{"ns"}, Categories: nil},
		{Name: "namespaces/status", SingularName: "", Namespaced: false, Kind: "Namespace", Verbs: metav1.Verbs{"get", "patch", "update"}, ShortNames: nil, Categories: nil},
		{Name: "nodes", SingularName: "node", Namespaced: false, Kind: "Node", Verbs: metav1.Verbs{"create", "delete", "deletecollection", "get", "list", "patch", "update", "watch"}, ShortNames: []string{"no"}, Categories: nil},
		{Name: "nodes/status", SingularName: "", Namespaced: false, Kind: "Node", Verbs: metav1.Verbs{"get", "patch", "update"}, ShortNames: nil, Categories: nil},
		{Name: "pods", SingularName: "pod", Namespaced: true, Kind: "Pod", Verbs: metav1.Verbs{"create", "delete", "deletecollection", "get", "list", "patch", "update", "watch"}, ShortNames: []string{"po"}, Categories: []string{"all"}},
		{Name: "pods/binding", SingularName: "", Namespaced: true, Kind: "Binding", Verbs: metav1.Verbs{"create"}, ShortNames: nil, Categories: nil},
		{Name: "pods/log", SingularName: "", Namespaced: true, Kind: "Pod", Verbs: metav1.Verbs{"get"}, ShortNames: nil, Categories: nil},
		{Name: "pods/status", SingularName: "", Namespaced: true, Kind: "Pod", Verbs: metav1.Verbs{"get", "patch", "update"}, ShortNames: nil, Categories: nil},
		{Name: "replicationcontrollers", SingularName: "replicationcontroller", Namespaced: true, Kind: "ReplicationController", Verbs: metav1.Verbs{"create", "delete", "deletecollection", "get", "list", "patch", "update", "watch"}, ShortNames: []string{"rc"}, Categories: []string{"all"}},
		{Name: "replicationcontrollers/status", SingularName: "", Namespaced: true, Kind: "ReplicationController", Verbs: metav1.Verbs{"get", "patch", "update"}, ShortNames: nil, Categories: nil},
		{Name: "secrets", SingularName: "secret", Namespaced: true, Kind: "Secret", Verbs: metav1.Verbs{"create", "delete", "deletecollection", "get", "list", "patch", "update", "watch"}, ShortNames: nil, Categories: nil},
		{Name: "serviceaccounts", SingularName: "serviceaccount", Namespaced: true, Kind: "ServiceAccount", Verbs: metav1.Verbs{"create", "delete", "deletecollection", "get", "list", "patch", "update", "watch"}, ShortNames: []string{"sa"}, Categories: nil},
		{Name: "services", SingularName: "service", Namespaced: true, Kind: "Service", Verbs: metav1.Verbs{"create", "delete", "deletecollection", "get", "list", "patch", "update", "watch"}, ShortNames: []string{"svc"}, Categories: []string{"all"}},
		{Name: "services/status", SingularName: "", Namespaced: true, Kind: "Service", Verbs: metav1.Verbs{"get", "patch", "update"}, ShortNames: nil, Categories: nil},
	}},
	{GV: schema.GroupVersion{Group: "apps", Version: "v1"}, Resources: []metav1.APIResource{
		{Name: "replicasets", SingularName: "replicaset", Namespaced: true, Kind: "ReplicaSet", Verbs: metav1.Verbs{"create", "delete", "deletecollection", "get", "list", "patch", "update", "watch"}, ShortNames: []string{"rs"}, Categories: []string{"all"}},
		{Name: "replicasets/status", SingularName: "", Namespaced: true, Kind: "ReplicaSet", Verbs: metav1.Verbs{"get", "patch", "update"}, ShortNames: nil, Categories: nil},
		{Name: "statefulsets", SingularName: "statefulset", Namespaced: true, Kind: "StatefulSet", Verbs: metav1.Verbs{"create", "delete", "deletecollection", "get", "list", "patch", "update", "watch"}, ShortNames: []string{"sts"}, Categories: []string{"all"}},
		{Name: "statefulsets/status", SingularName: "", Namespaced: true, Kind: "StatefulSet", Verbs: metav1.Verbs{"get", "patch", "update"}, ShortNames: nil, Categories: nil},
	}},
	{GV: schema.GroupVersion{Group: "policy", Version: "v1"}, Resources: []metav1.APIResource{
		{Name: "poddisruptionbudgets", SingularName: "poddisruptionbudget", Namespaced: true, Kind: "PodDisruptionBudget", Verbs: metav1.Verbs{"create", "delete", "deletecollection", "get", "list", "patch", "update", "watch"}, ShortNames: []string{"pdb"}, Categories: nil},
		{Name: "poddisruptionbudgets/status", SingularName: "", Namespaced: true, Kind: "PodDisruptionBudget", Verbs: metav1.Verbs{"get", "patch", "update"}, ShortNames: nil, Categories: nil},
	}},
	{GV: schema.GroupVersion{Group: "resource.k8s.io", Version: "v1"}, Resources: []metav1.APIResource{
		{Name: "deviceclasses", SingularName: "deviceclass", Namespaced: false, Kind: "DeviceClass", Verbs: metav1.Verbs{"create", "delete", "deletecollection", "get", "list", "patch", "update", "watch"}, ShortNames: nil, Categories: nil},
		{Name: "resourceclaims", SingularName: "resourceclaim", Namespaced: true, Kind: "ResourceClaim", Verbs: metav1.Verbs{"create", "delete", "deletecollection", "get", "list", "patch", "update", "watch"}, ShortNames: nil, Categories: nil},
		{Name: "resourceclaims/status", SingularName: "", Namespaced: true, Kind: "ResourceClaim", Verbs: metav1.Verbs{"get", "patch", "update"}, ShortNames: nil, Categories: nil},
		{Name: "resourceclaimtemplates", SingularName: "resourceclaimtemplate", Namespaced: true, Kind: "ResourceClaimTemplate", Verbs: metav1.Verbs{"create", "delete", "deletecollection", "get", "list", "patch", "update", "watch"}, ShortNames: nil, Categories: nil},
		{Name: "resourceslices", SingularName: "resourceslice", Namespaced: false, Kind: "ResourceSlice", Verbs: metav1.Verbs{"create", "delete", "deletecollection", "get", "list", "patch", "update", "watch"}, ShortNames: nil, Categories: nil},
	}},
	{GV: schema.GroupVersion{Group: "coordination.k8s.io", Version: "v1"}, Resources: []metav1.APIResource{
		{Name: "leases", SingularName: "lease", Namespaced: true, Kind: "Lease", Verbs: metav1.Verbs{"create", "delete", "deletecollection", "get", "list", "patch", "update", "watch"}, ShortNames: nil, Categories: nil},
	}},
	{GV: schema.GroupVersion{Group: "discovery.k8s.io", Version: "v1"}, Resources: []metav1.APIResource{
		{Name: "endpointslices", SingularName: "endpointslice", Namespaced: true, Kind: "EndpointSlice", Verbs: metav1.Verbs{"create", "delete", "deletecollection", "get", "list", "patch", "update", "watch"}, ShortNames: nil, Categories: nil},
	}},
	{GV: schema.GroupVersion{Group: "node.k8s.io", Version: "v1"}, Resources: []metav1.APIResource{
		{Name: "runtimeclasses", SingularName: "runtimeclass", Namespaced: false, Kind: "RuntimeClass", Verbs: metav1.Verbs{"create", "delete", "deletecollection", "get", "list", "patch", "update", "watch"}, ShortNames: nil, Categories: nil},
	}},
	{GV: schema.GroupVersion{Group: "storage.k8s.io", Version: "v1"}, Resources: []metav1.APIResource{
		{Name: "csidrivers", SingularName: "csidriver", Namespaced: false, Kind: "CSIDriver", Verbs: metav1.Verbs{"create", "delete", "deletecollection", "get", "list", "patch", "update", "watch"}, ShortNames: nil, Categories: nil},
		{Name: "csinodes", SingularName: "csinode", Namespaced: false, Kind: "CSINode", Verbs: metav1.Verbs{"create", "delete", "deletecollection", "get", "list", "patch", "update", "watch"}, ShortNames: nil, Categories: nil},
	}},
	{GV: schema.GroupVersion{Group: "authentication.k8s.io", Version: "v1"}, Resources: []metav1.APIResource{
		{Name: "tokenreviews", SingularName: "tokenreview", Namespaced: false, Kind: "TokenReview", Verbs: metav1.Verbs{"create"}, ShortNames: nil, Categories: nil},
	}},
	{GV: schema.GroupVersion{Group: "authorization.k8s.io", Version: "v1"}, Resources: []metav1.APIResource{
		{Name: "selfsubjectaccessreviews", SingularName: "selfsubjectaccessreview", Namespaced: false, Kind: "SelfSubjectAccessReview", Verbs: metav1.Verbs{"create"}, ShortNames: nil, Categories: nil},
		{Name: "subjectaccessreviews", SingularName: "subjectaccessreview", Namespaced: false, Kind: "SubjectAccessReview", Verbs: metav1.Verbs{"create"}, ShortNames: nil, Categories: nil},
	}},
	{GV: schema.GroupVersion{Group: "rbac.authorization.k8s.io", Version: "v1"}, Resources: []metav1.APIResource{
		{Name: "clusterrolebindings", SingularName: "clusterrolebinding", Namespaced: false, Kind: "ClusterRoleBinding", Verbs: metav1.Verbs{"create", "delete", "deletecollection", "get", "list", "patch", "update", "watch"}, ShortNames: nil, Categories: nil},
		{Name: "clusterroles", SingularName: "clusterrole", Namespaced: false, Kind: "ClusterRole", Verbs: metav1.Verbs{"create", "delete", "deletecollection", "get", "list", "patch", "update", "watch"}, ShortNames: nil, Categories: nil},
		{Name: "rolebindings", SingularName: "rolebinding", Namespaced: true, Kind: "RoleBinding", Verbs: metav1.Verbs{"create", "delete", "deletecollection", "get", "list", "patch", "update", "watch"}, ShortNames: nil, Categories: nil},
		{Name: "roles", SingularName: "role", Namespaced: true, Kind: "Role", Verbs: metav1.Verbs{"create", "delete", "deletecollection", "get", "list", "patch", "update", "watch"}, ShortNames: nil, Categories: nil},
	}},
}
