// Code generated by scripts/genresources from github.com/k3s-io/kubernetes@v1.36.4-k3s1 api/discovery. DO NOT EDIT.

package registry

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"
)

// Served is the API surface, filtered from upstream's discovery documents.
var Served = []ServedGroupVersion{
	{GV: schema.GroupVersion{Group: "", Version: "v1"}, Resources: []metav1.APIResource{
		{Name: "bindings", SingularName: "binding", Namespaced: true, Kind: "Binding", Verbs: metav1.Verbs{"create"}, ShortNames: nil, Categories: nil},
		{Name: "componentstatuses", SingularName: "componentstatus", Namespaced: false, Kind: "ComponentStatus", Verbs: metav1.Verbs{"get", "list"}, ShortNames: []string{"cs"}, Categories: nil},
		{Name: "configmaps", SingularName: "configmap", Namespaced: true, Kind: "ConfigMap", Verbs: metav1.Verbs{"create", "delete", "deletecollection", "get", "list", "patch", "update", "watch"}, ShortNames: []string{"cm"}, Categories: nil},
		{Name: "endpoints", SingularName: "endpoints", Namespaced: true, Kind: "Endpoints", Verbs: metav1.Verbs{"create", "delete", "deletecollection", "get", "list", "patch", "update", "watch"}, ShortNames: []string{"ep"}, Categories: nil},
		{Name: "events", SingularName: "event", Namespaced: true, Kind: "Event", Verbs: metav1.Verbs{"create", "delete", "deletecollection", "get", "list", "patch", "update", "watch"}, ShortNames: []string{"ev"}, Categories: nil},
		{Name: "limitranges", SingularName: "limitrange", Namespaced: true, Kind: "LimitRange", Verbs: metav1.Verbs{"create", "delete", "deletecollection", "get", "list", "patch", "update", "watch"}, ShortNames: []string{"limits"}, Categories: nil},
		{Name: "namespaces", SingularName: "namespace", Namespaced: false, Kind: "Namespace", Verbs: metav1.Verbs{"create", "delete", "get", "list", "patch", "update", "watch"}, ShortNames: []string{"ns"}, Categories: nil},
		{Name: "namespaces/finalize", SingularName: "", Namespaced: false, Kind: "Namespace", Verbs: metav1.Verbs{"update"}, ShortNames: nil, Categories: nil},
		{Name: "namespaces/status", SingularName: "", Namespaced: false, Kind: "Namespace", Verbs: metav1.Verbs{"get", "patch", "update"}, ShortNames: nil, Categories: nil},
		{Name: "nodes", SingularName: "node", Namespaced: false, Kind: "Node", Verbs: metav1.Verbs{"create", "delete", "deletecollection", "get", "list", "patch", "update", "watch"}, ShortNames: []string{"no"}, Categories: nil},
		{Name: "nodes/proxy", SingularName: "", Namespaced: false, Kind: "NodeProxyOptions", Verbs: metav1.Verbs{"create", "delete", "get", "patch", "update"}, ShortNames: nil, Categories: nil},
		{Name: "nodes/status", SingularName: "", Namespaced: false, Kind: "Node", Verbs: metav1.Verbs{"get", "patch", "update"}, ShortNames: nil, Categories: nil},
		{Name: "persistentvolumeclaims", SingularName: "persistentvolumeclaim", Namespaced: true, Kind: "PersistentVolumeClaim", Verbs: metav1.Verbs{"create", "delete", "deletecollection", "get", "list", "patch", "update", "watch"}, ShortNames: []string{"pvc"}, Categories: nil},
		{Name: "persistentvolumeclaims/status", SingularName: "", Namespaced: true, Kind: "PersistentVolumeClaim", Verbs: metav1.Verbs{"get", "patch", "update"}, ShortNames: nil, Categories: nil},
		{Name: "persistentvolumes", SingularName: "persistentvolume", Namespaced: false, Kind: "PersistentVolume", Verbs: metav1.Verbs{"create", "delete", "deletecollection", "get", "list", "patch", "update", "watch"}, ShortNames: []string{"pv"}, Categories: nil},
		{Name: "persistentvolumes/status", SingularName: "", Namespaced: false, Kind: "PersistentVolume", Verbs: metav1.Verbs{"get", "patch", "update"}, ShortNames: nil, Categories: nil},
		{Name: "pods", SingularName: "pod", Namespaced: true, Kind: "Pod", Verbs: metav1.Verbs{"create", "delete", "deletecollection", "get", "list", "patch", "update", "watch"}, ShortNames: []string{"po"}, Categories: []string{"all"}},
		{Name: "pods/attach", SingularName: "", Namespaced: true, Kind: "PodAttachOptions", Verbs: metav1.Verbs{"create", "get"}, ShortNames: nil, Categories: nil},
		{Name: "pods/binding", SingularName: "", Namespaced: true, Kind: "Binding", Verbs: metav1.Verbs{"create"}, ShortNames: nil, Categories: nil},
		{Name: "pods/ephemeralcontainers", SingularName: "", Namespaced: true, Kind: "Pod", Verbs: metav1.Verbs{"get", "patch", "update"}, ShortNames: nil, Categories: nil},
		{Name: "pods/eviction", SingularName: "", Namespaced: true, Kind: "Eviction", Verbs: metav1.Verbs{"create"}, ShortNames: nil, Categories: nil},
		{Name: "pods/exec", SingularName: "", Namespaced: true, Kind: "PodExecOptions", Verbs: metav1.Verbs{"create", "get"}, ShortNames: nil, Categories: nil},
		{Name: "pods/log", SingularName: "", Namespaced: true, Kind: "Pod", Verbs: metav1.Verbs{"get"}, ShortNames: nil, Categories: nil},
		{Name: "pods/portforward", SingularName: "", Namespaced: true, Kind: "PodPortForwardOptions", Verbs: metav1.Verbs{"create", "get"}, ShortNames: nil, Categories: nil},
		{Name: "pods/proxy", SingularName: "", Namespaced: true, Kind: "PodProxyOptions", Verbs: metav1.Verbs{"create", "delete", "get", "patch", "update"}, ShortNames: nil, Categories: nil},
		{Name: "pods/resize", SingularName: "", Namespaced: true, Kind: "Pod", Verbs: metav1.Verbs{"get", "patch", "update"}, ShortNames: nil, Categories: nil},
		{Name: "pods/status", SingularName: "", Namespaced: true, Kind: "Pod", Verbs: metav1.Verbs{"get", "patch", "update"}, ShortNames: nil, Categories: nil},
		{Name: "podtemplates", SingularName: "podtemplate", Namespaced: true, Kind: "PodTemplate", Verbs: metav1.Verbs{"create", "delete", "deletecollection", "get", "list", "patch", "update", "watch"}, ShortNames: nil, Categories: nil},
		{Name: "replicationcontrollers", SingularName: "replicationcontroller", Namespaced: true, Kind: "ReplicationController", Verbs: metav1.Verbs{"create", "delete", "deletecollection", "get", "list", "patch", "update", "watch"}, ShortNames: []string{"rc"}, Categories: []string{"all"}},
		{Name: "replicationcontrollers/scale", SingularName: "", Namespaced: true, Kind: "Scale", Verbs: metav1.Verbs{"get", "patch", "update"}, ShortNames: nil, Categories: nil},
		{Name: "replicationcontrollers/status", SingularName: "", Namespaced: true, Kind: "ReplicationController", Verbs: metav1.Verbs{"get", "patch", "update"}, ShortNames: nil, Categories: nil},
		{Name: "resourcequotas", SingularName: "resourcequota", Namespaced: true, Kind: "ResourceQuota", Verbs: metav1.Verbs{"create", "delete", "deletecollection", "get", "list", "patch", "update", "watch"}, ShortNames: []string{"quota"}, Categories: nil},
		{Name: "resourcequotas/status", SingularName: "", Namespaced: true, Kind: "ResourceQuota", Verbs: metav1.Verbs{"get", "patch", "update"}, ShortNames: nil, Categories: nil},
		{Name: "secrets", SingularName: "secret", Namespaced: true, Kind: "Secret", Verbs: metav1.Verbs{"create", "delete", "deletecollection", "get", "list", "patch", "update", "watch"}, ShortNames: nil, Categories: nil},
		{Name: "serviceaccounts", SingularName: "serviceaccount", Namespaced: true, Kind: "ServiceAccount", Verbs: metav1.Verbs{"create", "delete", "deletecollection", "get", "list", "patch", "update", "watch"}, ShortNames: []string{"sa"}, Categories: nil},
		{Name: "serviceaccounts/token", SingularName: "", Namespaced: true, Kind: "TokenRequest", Verbs: metav1.Verbs{"create"}, ShortNames: nil, Categories: nil},
		{Name: "services", SingularName: "service", Namespaced: true, Kind: "Service", Verbs: metav1.Verbs{"create", "delete", "deletecollection", "get", "list", "patch", "update", "watch"}, ShortNames: []string{"svc"}, Categories: []string{"all"}},
		{Name: "services/proxy", SingularName: "", Namespaced: true, Kind: "ServiceProxyOptions", Verbs: metav1.Verbs{"create", "delete", "get", "patch", "update"}, ShortNames: nil, Categories: nil},
		{Name: "services/status", SingularName: "", Namespaced: true, Kind: "Service", Verbs: metav1.Verbs{"get", "patch", "update"}, ShortNames: nil, Categories: nil},
	}},
	{GV: schema.GroupVersion{Group: "events.k8s.io", Version: "v1"}, Resources: []metav1.APIResource{
		{Name: "events", SingularName: "event", Namespaced: true, Kind: "Event", Verbs: metav1.Verbs{"create", "delete", "deletecollection", "get", "list", "patch", "update", "watch"}, ShortNames: []string{"ev"}, Categories: nil},
	}},
	{GV: schema.GroupVersion{Group: "apps", Version: "v1"}, Resources: []metav1.APIResource{
		{Name: "controllerrevisions", SingularName: "controllerrevision", Namespaced: true, Kind: "ControllerRevision", Verbs: metav1.Verbs{"create", "delete", "deletecollection", "get", "list", "patch", "update", "watch"}, ShortNames: nil, Categories: nil},
		{Name: "daemonsets", SingularName: "daemonset", Namespaced: true, Kind: "DaemonSet", Verbs: metav1.Verbs{"create", "delete", "deletecollection", "get", "list", "patch", "update", "watch"}, ShortNames: []string{"ds"}, Categories: []string{"all"}},
		{Name: "daemonsets/status", SingularName: "", Namespaced: true, Kind: "DaemonSet", Verbs: metav1.Verbs{"get", "patch", "update"}, ShortNames: nil, Categories: nil},
		{Name: "deployments", SingularName: "deployment", Namespaced: true, Kind: "Deployment", Verbs: metav1.Verbs{"create", "delete", "deletecollection", "get", "list", "patch", "update", "watch"}, ShortNames: []string{"deploy"}, Categories: []string{"all"}},
		{Name: "deployments/scale", SingularName: "", Namespaced: true, Kind: "Scale", Verbs: metav1.Verbs{"get", "patch", "update"}, ShortNames: nil, Categories: nil},
		{Name: "deployments/status", SingularName: "", Namespaced: true, Kind: "Deployment", Verbs: metav1.Verbs{"get", "patch", "update"}, ShortNames: nil, Categories: nil},
		{Name: "replicasets", SingularName: "replicaset", Namespaced: true, Kind: "ReplicaSet", Verbs: metav1.Verbs{"create", "delete", "deletecollection", "get", "list", "patch", "update", "watch"}, ShortNames: []string{"rs"}, Categories: []string{"all"}},
		{Name: "replicasets/scale", SingularName: "", Namespaced: true, Kind: "Scale", Verbs: metav1.Verbs{"get", "patch", "update"}, ShortNames: nil, Categories: nil},
		{Name: "replicasets/status", SingularName: "", Namespaced: true, Kind: "ReplicaSet", Verbs: metav1.Verbs{"get", "patch", "update"}, ShortNames: nil, Categories: nil},
		{Name: "statefulsets", SingularName: "statefulset", Namespaced: true, Kind: "StatefulSet", Verbs: metav1.Verbs{"create", "delete", "deletecollection", "get", "list", "patch", "update", "watch"}, ShortNames: []string{"sts"}, Categories: []string{"all"}},
		{Name: "statefulsets/scale", SingularName: "", Namespaced: true, Kind: "Scale", Verbs: metav1.Verbs{"get", "patch", "update"}, ShortNames: nil, Categories: nil},
		{Name: "statefulsets/status", SingularName: "", Namespaced: true, Kind: "StatefulSet", Verbs: metav1.Verbs{"get", "patch", "update"}, ShortNames: nil, Categories: nil},
	}},
	{GV: schema.GroupVersion{Group: "batch", Version: "v1"}, Resources: []metav1.APIResource{
		{Name: "cronjobs", SingularName: "cronjob", Namespaced: true, Kind: "CronJob", Verbs: metav1.Verbs{"create", "delete", "deletecollection", "get", "list", "patch", "update", "watch"}, ShortNames: []string{"cj"}, Categories: []string{"all"}},
		{Name: "cronjobs/status", SingularName: "", Namespaced: true, Kind: "CronJob", Verbs: metav1.Verbs{"get", "patch", "update"}, ShortNames: nil, Categories: nil},
		{Name: "jobs", SingularName: "job", Namespaced: true, Kind: "Job", Verbs: metav1.Verbs{"create", "delete", "deletecollection", "get", "list", "patch", "update", "watch"}, ShortNames: nil, Categories: []string{"all"}},
		{Name: "jobs/scale", SingularName: "", Namespaced: true, Kind: "Scale", Verbs: metav1.Verbs{"get", "patch", "update"}, ShortNames: nil, Categories: nil},
		{Name: "jobs/status", SingularName: "", Namespaced: true, Kind: "Job", Verbs: metav1.Verbs{"get", "patch", "update"}, ShortNames: nil, Categories: nil},
	}},
	{GV: schema.GroupVersion{Group: "autoscaling", Version: "v2"}, Resources: []metav1.APIResource{
		{Name: "horizontalpodautoscalers", SingularName: "horizontalpodautoscaler", Namespaced: true, Kind: "HorizontalPodAutoscaler", Verbs: metav1.Verbs{"create", "delete", "deletecollection", "get", "list", "patch", "update", "watch"}, ShortNames: []string{"hpa"}, Categories: []string{"all"}},
		{Name: "horizontalpodautoscalers/status", SingularName: "", Namespaced: true, Kind: "HorizontalPodAutoscaler", Verbs: metav1.Verbs{"get", "patch", "update"}, ShortNames: nil, Categories: nil},
	}},
	{GV: schema.GroupVersion{Group: "autoscaling", Version: "v1"}, Resources: []metav1.APIResource{
		{Name: "horizontalpodautoscalers", SingularName: "horizontalpodautoscaler", Namespaced: true, Kind: "HorizontalPodAutoscaler", Verbs: metav1.Verbs{"create", "delete", "deletecollection", "get", "list", "patch", "update", "watch"}, ShortNames: []string{"hpa"}, Categories: []string{"all"}},
		{Name: "horizontalpodautoscalers/status", SingularName: "", Namespaced: true, Kind: "HorizontalPodAutoscaler", Verbs: metav1.Verbs{"get", "patch", "update"}, ShortNames: nil, Categories: nil},
	}},
	{GV: schema.GroupVersion{Group: "policy", Version: "v1"}, Resources: []metav1.APIResource{
		{Name: "poddisruptionbudgets", SingularName: "poddisruptionbudget", Namespaced: true, Kind: "PodDisruptionBudget", Verbs: metav1.Verbs{"create", "delete", "deletecollection", "get", "list", "patch", "update", "watch"}, ShortNames: []string{"pdb"}, Categories: nil},
		{Name: "poddisruptionbudgets/status", SingularName: "", Namespaced: true, Kind: "PodDisruptionBudget", Verbs: metav1.Verbs{"get", "patch", "update"}, ShortNames: nil, Categories: nil},
	}},
	{GV: schema.GroupVersion{Group: "resource.k8s.io", Version: "v1"}, Resources: []metav1.APIResource{
		{Name: "deviceclasses", SingularName: "deviceclass", Namespaced: false, Kind: "DeviceClass", Verbs: metav1.Verbs{"create", "delete", "deletecollection", "get", "list", "patch", "update", "watch"}, ShortNames: nil, Categories: nil},
		{Name: "resourceclaims", SingularName: "resourceclaim", Namespaced: true, Kind: "ResourceClaim", Verbs: metav1.Verbs{"create", "delete", "deletecollection", "get", "list", "patch", "update", "watch"}, ShortNames: nil, Categories: nil},
		{Name: "resourceclaims/status", SingularName: "", Namespaced: true, Kind: "ResourceClaim", Verbs: metav1.Verbs{"get", "patch", "update"}, ShortNames: nil, Categories: nil},
		{Name: "resourceclaimtemplates", SingularName: "resourceclaimtemplate", Namespaced: true, Kind: "ResourceClaimTemplate", Verbs: metav1.Verbs{"create", "delete", "deletecollection", "get", "list", "patch", "update", "watch"}, ShortNames: nil, Categories: nil},
		{Name: "resourceslices", SingularName: "resourceslice", Namespaced: false, Kind: "ResourceSlice", Verbs: metav1.Verbs{"create", "delete", "deletecollection", "get", "list", "patch", "update", "watch"}, ShortNames: nil, Categories: nil},
	}},
	{GV: schema.GroupVersion{Group: "coordination.k8s.io", Version: "v1"}, Resources: []metav1.APIResource{
		{Name: "leases", SingularName: "lease", Namespaced: true, Kind: "Lease", Verbs: metav1.Verbs{"create", "delete", "deletecollection", "get", "list", "patch", "update", "watch"}, ShortNames: nil, Categories: nil},
	}},
	{GV: schema.GroupVersion{Group: "discovery.k8s.io", Version: "v1"}, Resources: []metav1.APIResource{
		{Name: "endpointslices", SingularName: "endpointslice", Namespaced: true, Kind: "EndpointSlice", Verbs: metav1.Verbs{"create", "delete", "deletecollection", "get", "list", "patch", "update", "watch"}, ShortNames: nil, Categories: nil},
	}},
	{GV: schema.GroupVersion{Group: "node.k8s.io", Version: "v1"}, Resources: []metav1.APIResource{
		{Name: "runtimeclasses", SingularName: "runtimeclass", Namespaced: false, Kind: "RuntimeClass", Verbs: metav1.Verbs{"create", "delete", "deletecollection", "get", "list", "patch", "update", "watch"}, ShortNames: nil, Categories: nil},
	}},
	{GV: schema.GroupVersion{Group: "storage.k8s.io", Version: "v1"}, Resources: []metav1.APIResource{
		{Name: "csidrivers", SingularName: "csidriver", Namespaced: false, Kind: "CSIDriver", Verbs: metav1.Verbs{"create", "delete", "deletecollection", "get", "list", "patch", "update", "watch"}, ShortNames: nil, Categories: nil},
		{Name: "csinodes", SingularName: "csinode", Namespaced: false, Kind: "CSINode", Verbs: metav1.Verbs{"create", "delete", "deletecollection", "get", "list", "patch", "update", "watch"}, ShortNames: nil, Categories: nil},
		{Name: "csistoragecapacities", SingularName: "csistoragecapacity", Namespaced: true, Kind: "CSIStorageCapacity", Verbs: metav1.Verbs{"create", "delete", "deletecollection", "get", "list", "patch", "update", "watch"}, ShortNames: nil, Categories: nil},
		{Name: "storageclasses", SingularName: "storageclass", Namespaced: false, Kind: "StorageClass", Verbs: metav1.Verbs{"create", "delete", "deletecollection", "get", "list", "patch", "update", "watch"}, ShortNames: []string{"sc"}, Categories: nil},
		{Name: "volumeattachments", SingularName: "volumeattachment", Namespaced: false, Kind: "VolumeAttachment", Verbs: metav1.Verbs{"create", "delete", "deletecollection", "get", "list", "patch", "update", "watch"}, ShortNames: nil, Categories: nil},
		{Name: "volumeattachments/status", SingularName: "", Namespaced: false, Kind: "VolumeAttachment", Verbs: metav1.Verbs{"get", "patch", "update"}, ShortNames: nil, Categories: nil},
		{Name: "volumeattributesclasses", SingularName: "volumeattributesclass", Namespaced: false, Kind: "VolumeAttributesClass", Verbs: metav1.Verbs{"create", "delete", "deletecollection", "get", "list", "patch", "update", "watch"}, ShortNames: []string{"vac"}, Categories: nil},
	}},
	{GV: schema.GroupVersion{Group: "authentication.k8s.io", Version: "v1"}, Resources: []metav1.APIResource{
		{Name: "selfsubjectreviews", SingularName: "selfsubjectreview", Namespaced: false, Kind: "SelfSubjectReview", Verbs: metav1.Verbs{"create"}, ShortNames: nil, Categories: nil},
		{Name: "tokenreviews", SingularName: "tokenreview", Namespaced: false, Kind: "TokenReview", Verbs: metav1.Verbs{"create"}, ShortNames: nil, Categories: nil},
	}},
	{GV: schema.GroupVersion{Group: "authorization.k8s.io", Version: "v1"}, Resources: []metav1.APIResource{
		{Name: "localsubjectaccessreviews", SingularName: "localsubjectaccessreview", Namespaced: true, Kind: "LocalSubjectAccessReview", Verbs: metav1.Verbs{"create"}, ShortNames: nil, Categories: nil},
		{Name: "selfsubjectaccessreviews", SingularName: "selfsubjectaccessreview", Namespaced: false, Kind: "SelfSubjectAccessReview", Verbs: metav1.Verbs{"create"}, ShortNames: nil, Categories: nil},
		{Name: "selfsubjectrulesreviews", SingularName: "selfsubjectrulesreview", Namespaced: false, Kind: "SelfSubjectRulesReview", Verbs: metav1.Verbs{"create"}, ShortNames: nil, Categories: nil},
		{Name: "subjectaccessreviews", SingularName: "subjectaccessreview", Namespaced: false, Kind: "SubjectAccessReview", Verbs: metav1.Verbs{"create"}, ShortNames: nil, Categories: nil},
	}},
	{GV: schema.GroupVersion{Group: "rbac.authorization.k8s.io", Version: "v1"}, Resources: []metav1.APIResource{
		{Name: "clusterrolebindings", SingularName: "clusterrolebinding", Namespaced: false, Kind: "ClusterRoleBinding", Verbs: metav1.Verbs{"create", "delete", "deletecollection", "get", "list", "patch", "update", "watch"}, ShortNames: nil, Categories: nil},
		{Name: "clusterroles", SingularName: "clusterrole", Namespaced: false, Kind: "ClusterRole", Verbs: metav1.Verbs{"create", "delete", "deletecollection", "get", "list", "patch", "update", "watch"}, ShortNames: nil, Categories: nil},
		{Name: "rolebindings", SingularName: "rolebinding", Namespaced: true, Kind: "RoleBinding", Verbs: metav1.Verbs{"create", "delete", "deletecollection", "get", "list", "patch", "update", "watch"}, ShortNames: nil, Categories: nil},
		{Name: "roles", SingularName: "role", Namespaced: true, Kind: "Role", Verbs: metav1.Verbs{"create", "delete", "deletecollection", "get", "list", "patch", "update", "watch"}, ShortNames: nil, Categories: nil},
	}},
	{GV: schema.GroupVersion{Group: "admissionregistration.k8s.io", Version: "v1"}, Resources: []metav1.APIResource{
		{Name: "mutatingadmissionpolicies", SingularName: "mutatingadmissionpolicy", Namespaced: false, Kind: "MutatingAdmissionPolicy", Verbs: metav1.Verbs{"create", "delete", "deletecollection", "get", "list", "patch", "update", "watch"}, ShortNames: nil, Categories: []string{"api-extensions"}},
		{Name: "mutatingadmissionpolicybindings", SingularName: "mutatingadmissionpolicybinding", Namespaced: false, Kind: "MutatingAdmissionPolicyBinding", Verbs: metav1.Verbs{"create", "delete", "deletecollection", "get", "list", "patch", "update", "watch"}, ShortNames: nil, Categories: []string{"api-extensions"}},
		{Name: "mutatingwebhookconfigurations", SingularName: "mutatingwebhookconfiguration", Namespaced: false, Kind: "MutatingWebhookConfiguration", Verbs: metav1.Verbs{"create", "delete", "deletecollection", "get", "list", "patch", "update", "watch"}, ShortNames: nil, Categories: []string{"api-extensions"}},
		{Name: "validatingadmissionpolicies", SingularName: "validatingadmissionpolicy", Namespaced: false, Kind: "ValidatingAdmissionPolicy", Verbs: metav1.Verbs{"create", "delete", "deletecollection", "get", "list", "patch", "update", "watch"}, ShortNames: nil, Categories: []string{"api-extensions"}},
		{Name: "validatingadmissionpolicies/status", SingularName: "", Namespaced: false, Kind: "ValidatingAdmissionPolicy", Verbs: metav1.Verbs{"get", "patch", "update"}, ShortNames: nil, Categories: nil},
		{Name: "validatingadmissionpolicybindings", SingularName: "validatingadmissionpolicybinding", Namespaced: false, Kind: "ValidatingAdmissionPolicyBinding", Verbs: metav1.Verbs{"create", "delete", "deletecollection", "get", "list", "patch", "update", "watch"}, ShortNames: nil, Categories: []string{"api-extensions"}},
		{Name: "validatingwebhookconfigurations", SingularName: "validatingwebhookconfiguration", Namespaced: false, Kind: "ValidatingWebhookConfiguration", Verbs: metav1.Verbs{"create", "delete", "deletecollection", "get", "list", "patch", "update", "watch"}, ShortNames: nil, Categories: []string{"api-extensions"}},
	}},
	{GV: schema.GroupVersion{Group: "scheduling.k8s.io", Version: "v1"}, Resources: []metav1.APIResource{
		{Name: "priorityclasses", SingularName: "priorityclass", Namespaced: false, Kind: "PriorityClass", Verbs: metav1.Verbs{"create", "delete", "deletecollection", "get", "list", "patch", "update", "watch"}, ShortNames: []string{"pc"}, Categories: nil},
	}},
	{GV: schema.GroupVersion{Group: "networking.k8s.io", Version: "v1"}, Resources: []metav1.APIResource{
		{Name: "ingressclasses", SingularName: "ingressclass", Namespaced: false, Kind: "IngressClass", Verbs: metav1.Verbs{"create", "delete", "deletecollection", "get", "list", "patch", "update", "watch"}, ShortNames: nil, Categories: nil},
		{Name: "ingresses", SingularName: "ingress", Namespaced: true, Kind: "Ingress", Verbs: metav1.Verbs{"create", "delete", "deletecollection", "get", "list", "patch", "update", "watch"}, ShortNames: []string{"ing"}, Categories: nil},
		{Name: "ingresses/status", SingularName: "", Namespaced: true, Kind: "Ingress", Verbs: metav1.Verbs{"get", "patch", "update"}, ShortNames: nil, Categories: nil},
		{Name: "ipaddresses", SingularName: "ipaddress", Namespaced: false, Kind: "IPAddress", Verbs: metav1.Verbs{"create", "delete", "deletecollection", "get", "list", "patch", "update", "watch"}, ShortNames: []string{"ip"}, Categories: nil},
		{Name: "networkpolicies", SingularName: "networkpolicy", Namespaced: true, Kind: "NetworkPolicy", Verbs: metav1.Verbs{"create", "delete", "deletecollection", "get", "list", "patch", "update", "watch"}, ShortNames: []string{"netpol"}, Categories: nil},
		{Name: "servicecidrs", SingularName: "servicecidr", Namespaced: false, Kind: "ServiceCIDR", Verbs: metav1.Verbs{"create", "delete", "deletecollection", "get", "list", "patch", "update", "watch"}, ShortNames: nil, Categories: nil},
		{Name: "servicecidrs/status", SingularName: "", Namespaced: false, Kind: "ServiceCIDR", Verbs: metav1.Verbs{"get", "patch", "update"}, ShortNames: nil, Categories: nil},
	}},
	{GV: schema.GroupVersion{Group: "certificates.k8s.io", Version: "v1"}, Resources: []metav1.APIResource{
		{Name: "certificatesigningrequests", SingularName: "certificatesigningrequest", Namespaced: false, Kind: "CertificateSigningRequest", Verbs: metav1.Verbs{"create", "delete", "deletecollection", "get", "list", "patch", "update", "watch"}, ShortNames: []string{"csr"}, Categories: nil},
		{Name: "certificatesigningrequests/approval", SingularName: "", Namespaced: false, Kind: "CertificateSigningRequest", Verbs: metav1.Verbs{"get", "patch", "update"}, ShortNames: nil, Categories: nil},
		{Name: "certificatesigningrequests/status", SingularName: "", Namespaced: false, Kind: "CertificateSigningRequest", Verbs: metav1.Verbs{"get", "patch", "update"}, ShortNames: nil, Categories: nil},
	}},
	{GV: schema.GroupVersion{Group: "flowcontrol.apiserver.k8s.io", Version: "v1"}, Resources: []metav1.APIResource{
		{Name: "flowschemas", SingularName: "flowschema", Namespaced: false, Kind: "FlowSchema", Verbs: metav1.Verbs{"create", "delete", "deletecollection", "get", "list", "patch", "update", "watch"}, ShortNames: nil, Categories: nil},
		{Name: "flowschemas/status", SingularName: "", Namespaced: false, Kind: "FlowSchema", Verbs: metav1.Verbs{"get", "patch", "update"}, ShortNames: nil, Categories: nil},
		{Name: "prioritylevelconfigurations", SingularName: "prioritylevelconfiguration", Namespaced: false, Kind: "PriorityLevelConfiguration", Verbs: metav1.Verbs{"create", "delete", "deletecollection", "get", "list", "patch", "update", "watch"}, ShortNames: nil, Categories: nil},
		{Name: "prioritylevelconfigurations/status", SingularName: "", Namespaced: false, Kind: "PriorityLevelConfiguration", Verbs: metav1.Verbs{"get", "patch", "update"}, ShortNames: nil, Categories: nil},
	}},
	{GV: schema.GroupVersion{Group: "apiregistration.k8s.io", Version: "v1"}, Resources: []metav1.APIResource{
		{Name: "apiservices", SingularName: "apiservice", Namespaced: false, Kind: "APIService", Verbs: metav1.Verbs{"create", "delete", "deletecollection", "get", "list", "patch", "update", "watch"}, ShortNames: nil, Categories: []string{"api-extensions"}},
		{Name: "apiservices/status", SingularName: "", Namespaced: false, Kind: "APIService", Verbs: metav1.Verbs{"get", "patch", "update"}, ShortNames: nil, Categories: nil},
	}},
}
