/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=packages/k8flare-worker/wrangler.jsonc --env-file=/dev/null --include-runtime=false --strict-vars=false packages/k8flare-worker/worker-configuration.d.ts` (hash: e8841199b1043c4d075a20b5e7d30883)
interface __BaseEnv_Env {
  LOADER: WorkerLoader;
  MESH: Fetcher;
  ASSETS: Fetcher;
  GATEWAY_URL: string;
  CLUSTER: DurableObjectNamespace<import("./src/index").Cluster>;
  WATCHHUB: DurableObjectNamespace<import("./src/index").WatchHub>;
  CONTROLLERS: DurableObjectNamespace<import("./src/index").Controllers>;
  REGISTRY: DurableObjectNamespace<import("./src/index").ClusterRegistry>;
  SCHEDULER: DurableObjectNamespace<import("./src/index").CFContainersScheduler>;
  NODE_VM_SMALL: DurableObjectNamespace<import("./src/index").NodeVMSmall>;
  NODE_VM_MEDIUM: DurableObjectNamespace<import("./src/index").NodeVMMedium>;
  NODE_VM_LARGE: DurableObjectNamespace<import("./src/index").NodeVMLarge>;
  SELF: Service<typeof import("./src/index").default>;
  STORAGE: Service<typeof import("./src/index").ClusterLoopback>;
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./src/index");
    durableNamespaces:
      | "Cluster"
      | "WatchHub"
      | "Controllers"
      | "ClusterRegistry"
      | "CFContainersScheduler"
      | "NodeVMSmall"
      | "NodeVMMedium"
      | "NodeVMLarge";
  }
  interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
